/** Auto-generated from scripts/generate-live-inventory.mjs — live stock sheet 2026-05-20 */
import type { Package } from "../types/catalog"

export const livePackages2026: Package[] = [
  {
    "id": "canada-paddock-club-red-bull-2026",
    "name": "3 Day Paddock Club - Red Bull",
    "circuit": "Canadian Grand Prix",
    "location": "Montreal",
    "country": "Canada",
    "countryCode": "CA",
    "date": "2026-05-24",
    "dateRange": "22 - 24 May",
    "price": 12950,
    "currency": "USD",
    "availability": "Enquire",
    "totalCapacity": 50,
    "image": "/images/circuits/montreal.jpg",
    "tier": "paddock",
    "duration": "3_day",
    "includes": [
      "Paddock Access",
      "Gourmet Dining",
      "Open Bar",
      "Pit Lane Walk"
    ],
    "featured": false,
    "raceId": "canada-2026"
  },
  {
    "id": "canada-paddock-club-team-haas-2026",
    "name": "3 Day Paddock Club - Team Haas",
    "circuit": "Canadian Grand Prix",
    "location": "Montreal",
    "country": "Canada",
    "countryCode": "CA",
    "date": "2026-05-24",
    "dateRange": "22 - 24 May",
    "price": 11999,
    "currency": "USD",
    "availability": "Enquire",
    "totalCapacity": 50,
    "image": "/images/circuits/montreal.jpg",
    "tier": "paddock",
    "duration": "3_day",
    "includes": [
      "Paddock Access",
      "Gourmet Dining",
      "Open Bar",
      "Pit Lane Walk"
    ],
    "featured": false,
    "raceId": "canada-2026"
  },
  {
    "id": "canada-paddock-club-club-suite-2026",
    "name": "3 Day Paddock Club - Club Suite",
    "circuit": "Canadian Grand Prix",
    "location": "Montreal",
    "country": "Canada",
    "countryCode": "CA",
    "date": "2026-05-24",
    "dateRange": "22 - 24 May",
    "price": 8625,
    "currency": "USD",
    "availability": "Enquire",
    "totalCapacity": 50,
    "image": "/images/circuits/montreal.jpg",
    "tier": "paddock",
    "duration": "3_day",
    "includes": [
      "Paddock Access",
      "Gourmet Dining",
      "Open Bar",
      "Pit Lane Walk"
    ],
    "featured": false,
    "raceId": "canada-2026"
  },
  {
    "id": "canada-f1-experience-lounge-elite-2026",
    "name": "3 Day F1 Experience Lounge Elite Suite",
    "circuit": "Canadian Grand Prix",
    "location": "Montreal",
    "country": "Canada",
    "countryCode": "CA",
    "date": "2026-05-24",
    "dateRange": "22 - 24 May",
    "price": 6437,
    "currency": "USD",
    "availability": "Enquire",
    "totalCapacity": 50,
    "image": "/images/circuits/montreal.jpg",
    "tier": "paddock",
    "duration": "3_day",
    "includes": [
      "Paddock Access",
      "Gourmet Dining",
      "Open Bar",
      "Pit Lane Walk"
    ],
    "featured": false,
    "raceId": "canada-2026"
  },
  {
    "id": "canada-champions-club-2026",
    "name": "3 Day Champions Club",
    "circuit": "Canadian Grand Prix",
    "location": "Montreal",
    "country": "Canada",
    "countryCode": "CA",
    "date": "2026-05-24",
    "dateRange": "22 - 24 May",
    "price": 6357,
    "currency": "USD",
    "availability": "Enquire",
    "totalCapacity": 50,
    "image": "/images/circuits/montreal.jpg",
    "tier": "champions",
    "duration": "3_day",
    "includes": [
      "Grandstand Seats",
      "Hospitality Suite",
      "Gourmet Lunch",
      "Pit Lane Walk"
    ],
    "featured": false,
    "raceId": "canada-2026"
  },
  {
    "id": "monaco-gordon-ramsey-terrasse-2026",
    "name": "3 Day Gordon Ramsey - La Terrasse",
    "circuit": "Monaco Grand Prix",
    "location": "Monte Carlo",
    "country": "Monaco",
    "countryCode": "MC",
    "date": "2026-06-07",
    "dateRange": "05 - 07 Jun",
    "price": 24000,
    "currency": "USD",
    "availability": "Enquire",
    "totalCapacity": 50,
    "image": "/images/circuits/monaco.jpg",
    "tier": "hero",
    "duration": "3_day",
    "includes": [
      "Hospitality Access",
      "Race Viewing",
      "Refreshments"
    ],
    "featured": false,
    "raceId": "monaco-2026"
  },
  {
    "id": "monaco-triple-crown-paddock-2026",
    "name": "3 Day Triple Crown - Paddock Club",
    "circuit": "Monaco Grand Prix",
    "location": "Monte Carlo",
    "country": "Monaco",
    "countryCode": "MC",
    "date": "2026-06-07",
    "dateRange": "05 - 07 Jun",
    "price": 21000,
    "currency": "USD",
    "availability": "Enquire",
    "totalCapacity": 50,
    "image": "/images/circuits/monaco.jpg",
    "tier": "paddock",
    "duration": "3_day",
    "includes": [
      "Paddock Access",
      "Gourmet Dining",
      "Open Bar",
      "Pit Lane Walk"
    ],
    "featured": false,
    "raceId": "monaco-2026"
  },
  {
    "id": "monaco-legend-paddock-club-2026",
    "name": "3 Day Legend Paddock Club - Club Suite",
    "circuit": "Monaco Grand Prix",
    "location": "Monte Carlo",
    "country": "Monaco",
    "countryCode": "MC",
    "date": "2026-06-07",
    "dateRange": "05 - 07 Jun",
    "price": 18999,
    "currency": "USD",
    "availability": "Enquire",
    "totalCapacity": 50,
    "image": "/images/circuits/monaco.jpg",
    "tier": "legend",
    "duration": "3_day",
    "includes": [
      "Paddock Club Access",
      "Premium Dining",
      "Open Bar",
      "Pit Lane Walk",
      "Driver Appearances"
    ],
    "featured": false,
    "raceId": "monaco-2026"
  },
  {
    "id": "monaco-audi-paddock-club-2026",
    "name": "3 Day Paddock Club - Audi",
    "circuit": "Monaco Grand Prix",
    "location": "Monte Carlo",
    "country": "Monaco",
    "countryCode": "MC",
    "date": "2026-06-07",
    "dateRange": "05 - 07 Jun",
    "price": 18689,
    "currency": "USD",
    "availability": "Enquire",
    "totalCapacity": 50,
    "image": "/images/circuits/monaco.jpg",
    "tier": "paddock",
    "duration": "3_day",
    "includes": [
      "Paddock Access",
      "Gourmet Dining",
      "Open Bar",
      "Pit Lane Walk"
    ],
    "featured": false,
    "raceId": "monaco-2026"
  },
  {
    "id": "monaco-team-haas-paddock-club-2026",
    "name": "3 Day Paddock Club - Team Haas",
    "circuit": "Monaco Grand Prix",
    "location": "Monte Carlo",
    "country": "Monaco",
    "countryCode": "MC",
    "date": "2026-06-07",
    "dateRange": "05 - 07 Jun",
    "price": 17759,
    "currency": "USD",
    "availability": "Enquire",
    "totalCapacity": 50,
    "image": "/images/circuits/monaco.jpg",
    "tier": "paddock",
    "duration": "3_day",
    "includes": [
      "Paddock Access",
      "Gourmet Dining",
      "Open Bar",
      "Pit Lane Walk"
    ],
    "featured": false,
    "raceId": "monaco-2026"
  },
  {
    "id": "monaco-paddock-club-trackside-yacht-2026",
    "name": "3 Day Paddock Club - Trackside Yacht",
    "circuit": "Monaco Grand Prix",
    "location": "Monte Carlo",
    "country": "Monaco",
    "countryCode": "MC",
    "date": "2026-06-07",
    "dateRange": "05 - 07 Jun",
    "price": 17750,
    "currency": "USD",
    "availability": "Enquire",
    "totalCapacity": 50,
    "image": "/images/circuits/monaco.jpg",
    "tier": "paddock",
    "duration": "3_day",
    "includes": [
      "Paddock Access",
      "Gourmet Dining",
      "Open Bar",
      "Pit Lane Walk"
    ],
    "featured": false,
    "raceId": "monaco-2026"
  },
  {
    "id": "monaco-paddock-club-club-suite-2026",
    "name": "3 Day Paddock Club - Club Suite",
    "circuit": "Monaco Grand Prix",
    "location": "Monte Carlo",
    "country": "Monaco",
    "countryCode": "MC",
    "date": "2026-06-07",
    "dateRange": "05 - 07 Jun",
    "price": 14159,
    "currency": "USD",
    "availability": "Enquire",
    "totalCapacity": 50,
    "image": "/images/circuits/monaco.jpg",
    "tier": "paddock",
    "duration": "3_day",
    "includes": [
      "Paddock Access",
      "Gourmet Dining",
      "Open Bar",
      "Pit Lane Walk"
    ],
    "featured": false,
    "raceId": "monaco-2026"
  },
  {
    "id": "monaco-paddock-club-house-44-2026",
    "name": "3 Day Paddock Club House 44",
    "circuit": "Monaco Grand Prix",
    "location": "Monte Carlo",
    "country": "Monaco",
    "countryCode": "MC",
    "date": "2026-06-07",
    "dateRange": "05 - 07 Jun",
    "price": 21000,
    "currency": "USD",
    "availability": 4,
    "totalCapacity": 30,
    "image": "/images/circuits/monaco.jpg",
    "tier": "paddock",
    "duration": "3_day",
    "includes": [
      "Paddock Access",
      "Gourmet Dining",
      "Open Bar",
      "Pit Lane Walk"
    ],
    "featured": false,
    "raceId": "monaco-2026"
  },
  {
    "id": "monaco-champions-2day-ermano-2026",
    "name": "2 Day Champions Club - Ermano Penthouse",
    "circuit": "Monaco Grand Prix",
    "location": "Monte Carlo",
    "country": "Monaco",
    "countryCode": "MC",
    "date": "2026-06-07",
    "dateRange": "05 - 07 Jun",
    "price": 7899,
    "currency": "USD",
    "availability": "Enquire",
    "totalCapacity": 50,
    "image": "/images/circuits/monaco.jpg",
    "tier": "champions",
    "duration": "2_day",
    "includes": [
      "Grandstand Seats",
      "Hospitality Suite",
      "Gourmet Lunch",
      "Pit Lane Walk"
    ],
    "featured": false,
    "raceId": "monaco-2026"
  },
  {
    "id": "monaco-champions-2day-trackside-yacht-2026",
    "name": "2 Day Champions Club - Trackside Yacht",
    "circuit": "Monaco Grand Prix",
    "location": "Monte Carlo",
    "country": "Monaco",
    "countryCode": "MC",
    "date": "2026-06-07",
    "dateRange": "05 - 07 Jun",
    "price": 7899,
    "currency": "USD",
    "availability": "Enquire",
    "totalCapacity": 50,
    "image": "/images/circuits/monaco.jpg",
    "tier": "champions",
    "duration": "2_day",
    "includes": [
      "Grandstand Seats",
      "Hospitality Suite",
      "Gourmet Lunch",
      "Pit Lane Walk"
    ],
    "featured": false,
    "raceId": "monaco-2026"
  },
  {
    "id": "monaco-velocity-terrace-sun-sat-2026",
    "name": "Saturday & Sunday Velocity Terrace",
    "circuit": "Monaco Grand Prix",
    "location": "Monte Carlo",
    "country": "Monaco",
    "countryCode": "MC",
    "date": "2026-06-07",
    "dateRange": "05 - 07 Jun",
    "price": 6500,
    "currency": "USD",
    "availability": 10,
    "totalCapacity": 30,
    "image": "/images/circuits/monaco.jpg",
    "tier": "hero",
    "duration": "2_day",
    "includes": [
      "Hospitality Access",
      "Race Viewing",
      "Refreshments"
    ],
    "featured": true,
    "raceId": "monaco-2026"
  },
  {
    "id": "monaco-velocity-terrace-sunday-2026",
    "name": "Sunday Velocity Terrace",
    "circuit": "Monaco Grand Prix",
    "location": "Monte Carlo",
    "country": "Monaco",
    "countryCode": "MC",
    "date": "2026-06-07",
    "dateRange": "05 - 07 Jun",
    "price": 4750,
    "currency": "USD",
    "availability": 10,
    "totalCapacity": 30,
    "image": "/images/circuits/monaco.jpg",
    "tier": "hero",
    "duration": "sunday_only",
    "includes": [
      "Hospitality Access",
      "Race Viewing",
      "Refreshments"
    ],
    "featured": false,
    "raceId": "monaco-2026"
  },
  {
    "id": "monaco-velocity-terrace-saturday-2026",
    "name": "Saturday Velocity Terrace",
    "circuit": "Monaco Grand Prix",
    "location": "Monte Carlo",
    "country": "Monaco",
    "countryCode": "MC",
    "date": "2026-06-07",
    "dateRange": "05 - 07 Jun",
    "price": 1995,
    "currency": "USD",
    "availability": 10,
    "totalCapacity": 30,
    "image": "/images/circuits/monaco.jpg",
    "tier": "hero",
    "duration": "saturday_only",
    "includes": [
      "Hospitality Access",
      "Race Viewing",
      "Refreshments"
    ],
    "featured": false,
    "raceId": "monaco-2026"
  },
  {
    "id": "monaco-amazonica-terrace-sunday-2026",
    "name": "Sunday Amazonica Terrace",
    "circuit": "Monaco Grand Prix",
    "location": "Monte Carlo",
    "country": "Monaco",
    "countryCode": "MC",
    "date": "2026-06-07",
    "dateRange": "05 - 07 Jun",
    "price": 4199,
    "currency": "USD",
    "availability": 10,
    "totalCapacity": 30,
    "image": "/images/circuits/monaco.jpg",
    "tier": "hero",
    "duration": "sunday_only",
    "includes": [
      "Hospitality Access",
      "Race Viewing",
      "Refreshments"
    ],
    "featured": false,
    "raceId": "monaco-2026"
  },
  {
    "id": "monaco-amazonica-terrace-saturday-2026",
    "name": "Saturday Amazonica Terrace",
    "circuit": "Monaco Grand Prix",
    "location": "Monte Carlo",
    "country": "Monaco",
    "countryCode": "MC",
    "date": "2026-06-07",
    "dateRange": "05 - 07 Jun",
    "price": 1900,
    "currency": "USD",
    "availability": 10,
    "totalCapacity": 30,
    "image": "/images/circuits/monaco.jpg",
    "tier": "hero",
    "duration": "saturday_only",
    "includes": [
      "Hospitality Access",
      "Race Viewing",
      "Refreshments"
    ],
    "featured": false,
    "raceId": "monaco-2026"
  },
  {
    "id": "barcelona-f1-experiences-house-44-2026",
    "name": "3 Day F1 Experiences House 44",
    "circuit": "Spanish Grand Prix",
    "location": "Barcelona",
    "country": "Spain",
    "countryCode": "ES",
    "date": "2026-06-14",
    "dateRange": "12 - 14 Jun",
    "price": 16335,
    "currency": "USD",
    "availability": "Enquire",
    "totalCapacity": 50,
    "image": "/images/circuits/barcelona.jpg",
    "tier": "paddock",
    "duration": "3_day",
    "includes": [
      "Paddock Access",
      "Gourmet Dining",
      "Open Bar",
      "Pit Lane Walk"
    ],
    "featured": false,
    "raceId": "spain-2026"
  },
  {
    "id": "barcelona-legend-paddock-club-2026",
    "name": "3 Day Legend Paddock Club",
    "circuit": "Spanish Grand Prix",
    "location": "Barcelona",
    "country": "Spain",
    "countryCode": "ES",
    "date": "2026-06-14",
    "dateRange": "12 - 14 Jun",
    "price": 10999,
    "currency": "USD",
    "availability": 10,
    "totalCapacity": 30,
    "image": "/images/circuits/barcelona.jpg",
    "tier": "legend",
    "duration": "3_day",
    "includes": [
      "Paddock Club Access",
      "Premium Dining",
      "Open Bar",
      "Pit Lane Walk",
      "Driver Appearances"
    ],
    "featured": false,
    "raceId": "spain-2026"
  },
  {
    "id": "barcelona-paddock-club-audi-2026",
    "name": "3 Day Paddock Club - Audi",
    "circuit": "Spanish Grand Prix",
    "location": "Barcelona",
    "country": "Spain",
    "countryCode": "ES",
    "date": "2026-06-14",
    "dateRange": "12 - 14 Jun",
    "price": 9889,
    "currency": "USD",
    "availability": "Enquire",
    "totalCapacity": 50,
    "image": "/images/circuits/barcelona.jpg",
    "tier": "paddock",
    "duration": "3_day",
    "includes": [
      "Paddock Access",
      "Gourmet Dining",
      "Open Bar",
      "Pit Lane Walk"
    ],
    "featured": false,
    "raceId": "spain-2026"
  },
  {
    "id": "barcelona-paddock-club-team-haas-2026",
    "name": "3 Day Paddock Club - Team Haas",
    "circuit": "Spanish Grand Prix",
    "location": "Barcelona",
    "country": "Spain",
    "countryCode": "ES",
    "date": "2026-06-14",
    "dateRange": "12 - 14 Jun",
    "price": 9679,
    "currency": "USD",
    "availability": "Enquire",
    "totalCapacity": 50,
    "image": "/images/circuits/barcelona.jpg",
    "tier": "paddock",
    "duration": "3_day",
    "includes": [
      "Paddock Access",
      "Gourmet Dining",
      "Open Bar",
      "Pit Lane Walk"
    ],
    "featured": false,
    "raceId": "spain-2026"
  },
  {
    "id": "barcelona-f1-experiences-paddock-club-2026",
    "name": "3 Day F1 Experiences Paddock Club",
    "circuit": "Spanish Grand Prix",
    "location": "Barcelona",
    "country": "Spain",
    "countryCode": "ES",
    "date": "2026-06-14",
    "dateRange": "12 - 14 Jun",
    "price": 7750,
    "currency": "USD",
    "availability": 10,
    "totalCapacity": 30,
    "image": "/images/circuits/barcelona.jpg",
    "tier": "paddock",
    "duration": "3_day",
    "includes": [
      "Paddock Access",
      "Gourmet Dining",
      "Open Bar",
      "Pit Lane Walk"
    ],
    "featured": false,
    "raceId": "spain-2026"
  },
  {
    "id": "barcelona-paddock-club-club-suite-f1-2026",
    "name": "3 Day Paddock Club - Club Suite (F1)",
    "circuit": "Spanish Grand Prix",
    "location": "Barcelona",
    "country": "Spain",
    "countryCode": "ES",
    "date": "2026-06-14",
    "dateRange": "12 - 14 Jun",
    "price": 6655,
    "currency": "USD",
    "availability": 7,
    "totalCapacity": 30,
    "image": "/images/circuits/barcelona.jpg",
    "tier": "paddock",
    "duration": "3_day",
    "includes": [
      "Paddock Access",
      "Gourmet Dining",
      "Open Bar",
      "Pit Lane Walk"
    ],
    "featured": false,
    "raceId": "spain-2026"
  },
  {
    "id": "barcelona-champions-club-2026",
    "name": "3 Day Champions Club",
    "circuit": "Spanish Grand Prix",
    "location": "Barcelona",
    "country": "Spain",
    "countryCode": "ES",
    "date": "2026-06-14",
    "dateRange": "12 - 14 Jun",
    "price": 4150,
    "currency": "USD",
    "availability": "Enquire",
    "totalCapacity": 50,
    "image": "/images/circuits/barcelona.jpg",
    "tier": "champions",
    "duration": "3_day",
    "includes": [
      "Grandstand Seats",
      "Hospitality Suite",
      "Gourmet Lunch",
      "Pit Lane Walk"
    ],
    "featured": false,
    "raceId": "spain-2026"
  },
  {
    "id": "austria-legend-paddock-club-2026",
    "name": "3 Day Legend Paddock Club",
    "circuit": "Austrian Grand Prix",
    "location": "Spielberg",
    "country": "Austria",
    "countryCode": "AT",
    "date": "2026-06-28",
    "dateRange": "26 - 28 Jun",
    "price": 11138,
    "currency": "USD",
    "availability": "Enquire",
    "totalCapacity": 50,
    "image": "/images/circuits/spielberg.jpg",
    "tier": "legend",
    "duration": "3_day",
    "includes": [
      "Paddock Club Access",
      "Premium Dining",
      "Open Bar",
      "Pit Lane Walk",
      "Driver Appearances"
    ],
    "featured": false,
    "raceId": "austria-2026"
  },
  {
    "id": "austria-f1-experiences-audi-club-suite-2026",
    "name": "3 Day F1 Experiences Audi F1 Club Suite",
    "circuit": "Austrian Grand Prix",
    "location": "Spielberg",
    "country": "Austria",
    "countryCode": "AT",
    "date": "2026-06-28",
    "dateRange": "26 - 28 Jun",
    "price": 9449,
    "currency": "USD",
    "availability": "Enquire",
    "totalCapacity": 50,
    "image": "/images/circuits/spielberg.jpg",
    "tier": "paddock",
    "duration": "3_day",
    "includes": [
      "Paddock Access",
      "Gourmet Dining",
      "Open Bar",
      "Pit Lane Walk"
    ],
    "featured": false,
    "raceId": "austria-2026"
  },
  {
    "id": "austria-f1-experiences-team-haas-2026",
    "name": "3 Day F1 Experiences Team Haas",
    "circuit": "Austrian Grand Prix",
    "location": "Spielberg",
    "country": "Austria",
    "countryCode": "AT",
    "date": "2026-06-28",
    "dateRange": "26 - 28 Jun",
    "price": 9239,
    "currency": "USD",
    "availability": "Enquire",
    "totalCapacity": 50,
    "image": "/images/circuits/spielberg.jpg",
    "tier": "paddock",
    "duration": "3_day",
    "includes": [
      "Paddock Access",
      "Gourmet Dining",
      "Open Bar",
      "Pit Lane Walk"
    ],
    "featured": false,
    "raceId": "austria-2026"
  },
  {
    "id": "austria-f1-experiences-paddock-club-2026",
    "name": "3 Day F1 Experiences Paddock Club",
    "circuit": "Austrian Grand Prix",
    "location": "Spielberg",
    "country": "Austria",
    "countryCode": "AT",
    "date": "2026-06-28",
    "dateRange": "26 - 28 Jun",
    "price": 7500,
    "currency": "USD",
    "availability": 4,
    "totalCapacity": 30,
    "image": "/images/circuits/spielberg.jpg",
    "tier": "paddock",
    "duration": "3_day",
    "includes": [
      "Paddock Access",
      "Gourmet Dining",
      "Open Bar",
      "Pit Lane Walk"
    ],
    "featured": false,
    "raceId": "austria-2026"
  },
  {
    "id": "austria-paddock-club-club-suite-f1-2026",
    "name": "3 Day Paddock Club - Club Suite (F1)",
    "circuit": "Austrian Grand Prix",
    "location": "Spielberg",
    "country": "Austria",
    "countryCode": "AT",
    "date": "2026-06-28",
    "dateRange": "26 - 28 Jun",
    "price": 6900,
    "currency": "USD",
    "availability": 8,
    "totalCapacity": 30,
    "image": "/images/circuits/spielberg.jpg",
    "tier": "paddock",
    "duration": "3_day",
    "includes": [
      "Paddock Access",
      "Gourmet Dining",
      "Open Bar",
      "Pit Lane Walk"
    ],
    "featured": false,
    "raceId": "austria-2026"
  },
  {
    "id": "austria-champions-club-2026",
    "name": "3 Day Champions Club",
    "circuit": "Austrian Grand Prix",
    "location": "Spielberg",
    "country": "Austria",
    "countryCode": "AT",
    "date": "2026-06-28",
    "dateRange": "26 - 28 Jun",
    "price": 3899,
    "currency": "USD",
    "availability": 10,
    "totalCapacity": 30,
    "image": "/images/circuits/spielberg.jpg",
    "tier": "champions",
    "duration": "3_day",
    "includes": [
      "Grandstand Seats",
      "Hospitality Suite",
      "Gourmet Lunch",
      "Pit Lane Walk"
    ],
    "featured": false,
    "raceId": "austria-2026"
  },
  {
    "id": "britain-gordon-ramsey-f1-lounge-2026",
    "name": "3 Day Gordon Ramsey at F1 Lounge",
    "circuit": "British Grand Prix",
    "location": "Silverstone",
    "country": "United Kingdom",
    "countryCode": "GB",
    "date": "2026-07-05",
    "dateRange": "03 - 05 Jul",
    "price": 36000,
    "currency": "USD",
    "availability": "Enquire",
    "totalCapacity": 50,
    "image": "/images/circuits/silverstone.jpg",
    "tier": "hero",
    "duration": "3_day",
    "includes": [
      "Hospitality Access",
      "Race Viewing",
      "Refreshments"
    ],
    "featured": false,
    "raceId": "britain-2026"
  },
  {
    "id": "britain-legend-paddock-club-2026",
    "name": "3 Day Legend Paddock Club",
    "circuit": "British Grand Prix",
    "location": "Silverstone",
    "country": "United Kingdom",
    "countryCode": "GB",
    "date": "2026-07-05",
    "dateRange": "03 - 05 Jul",
    "price": 13379,
    "currency": "USD",
    "availability": "Enquire",
    "totalCapacity": 50,
    "image": "/images/circuits/silverstone.jpg",
    "tier": "legend",
    "duration": "3_day",
    "includes": [
      "Paddock Club Access",
      "Premium Dining",
      "Open Bar",
      "Pit Lane Walk",
      "Driver Appearances"
    ],
    "featured": false,
    "raceId": "britain-2026"
  },
  {
    "id": "britain-paddock-club-house-44-2026",
    "name": "3 Day Paddock Club House 44",
    "circuit": "British Grand Prix",
    "location": "Silverstone",
    "country": "United Kingdom",
    "countryCode": "GB",
    "date": "2026-07-05",
    "dateRange": "03 - 05 Jul",
    "price": 16200,
    "currency": "USD",
    "availability": "Enquire",
    "totalCapacity": 50,
    "image": "/images/circuits/silverstone.jpg",
    "tier": "paddock",
    "duration": "3_day",
    "includes": [
      "Paddock Access",
      "Gourmet Dining",
      "Open Bar",
      "Pit Lane Walk"
    ],
    "featured": false,
    "raceId": "britain-2026"
  },
  {
    "id": "britain-paddock-club-red-bull-2026",
    "name": "3 Day Paddock Club - Red Bull",
    "circuit": "British Grand Prix",
    "location": "Silverstone",
    "country": "United Kingdom",
    "countryCode": "GB",
    "date": "2026-07-05",
    "dateRange": "03 - 05 Jul",
    "price": 13950,
    "currency": "USD",
    "availability": "Enquire",
    "totalCapacity": 50,
    "image": "/images/circuits/silverstone.jpg",
    "tier": "paddock",
    "duration": "3_day",
    "includes": [
      "Paddock Access",
      "Gourmet Dining",
      "Open Bar",
      "Pit Lane Walk"
    ],
    "featured": false,
    "raceId": "britain-2026"
  },
  {
    "id": "britain-paddock-club-team-haas-2026",
    "name": "3 Day Paddock Club - Team Haas",
    "circuit": "British Grand Prix",
    "location": "Silverstone",
    "country": "United Kingdom",
    "countryCode": "GB",
    "date": "2026-07-05",
    "dateRange": "03 - 05 Jul",
    "price": 10319,
    "currency": "USD",
    "availability": "Enquire",
    "totalCapacity": 50,
    "image": "/images/circuits/silverstone.jpg",
    "tier": "paddock",
    "duration": "3_day",
    "includes": [
      "Paddock Access",
      "Gourmet Dining",
      "Open Bar",
      "Pit Lane Walk"
    ],
    "featured": false,
    "raceId": "britain-2026"
  },
  {
    "id": "britain-f1-experiences-paddock-club-2026",
    "name": "3 Day F1 Experiences Paddock Club",
    "circuit": "British Grand Prix",
    "location": "Silverstone",
    "country": "United Kingdom",
    "countryCode": "GB",
    "date": "2026-07-05",
    "dateRange": "03 - 05 Jul",
    "price": 11995,
    "currency": "USD",
    "availability": 3,
    "totalCapacity": 30,
    "image": "/images/circuits/silverstone.jpg",
    "tier": "paddock",
    "duration": "3_day",
    "includes": [
      "Paddock Access",
      "Gourmet Dining",
      "Open Bar",
      "Pit Lane Walk"
    ],
    "featured": false,
    "raceId": "britain-2026"
  },
  {
    "id": "britain-paddock-club-alpine-2026",
    "name": "3 Day Paddock Club - Alpine",
    "circuit": "British Grand Prix",
    "location": "Silverstone",
    "country": "United Kingdom",
    "countryCode": "GB",
    "date": "2026-07-05",
    "dateRange": "03 - 05 Jul",
    "price": 10500,
    "currency": "USD",
    "availability": 2,
    "totalCapacity": 30,
    "image": "/images/circuits/silverstone.jpg",
    "tier": "paddock",
    "duration": "3_day",
    "includes": [
      "Paddock Access",
      "Gourmet Dining",
      "Open Bar",
      "Pit Lane Walk"
    ],
    "featured": false,
    "raceId": "britain-2026"
  },
  {
    "id": "britain-f1-experiences-lounge-2026",
    "name": "3 Day F1 Experiences Lounge",
    "circuit": "British Grand Prix",
    "location": "Silverstone",
    "country": "United Kingdom",
    "countryCode": "GB",
    "date": "2026-07-05",
    "dateRange": "03 - 05 Jul",
    "price": 4199,
    "currency": "USD",
    "availability": 10,
    "totalCapacity": 30,
    "image": "/images/circuits/silverstone.jpg",
    "tier": "paddock",
    "duration": "3_day",
    "includes": [
      "Paddock Access",
      "Gourmet Dining",
      "Open Bar",
      "Pit Lane Walk"
    ],
    "featured": false,
    "raceId": "britain-2026"
  },
  {
    "id": "belgium-legend-paddock-club-2026",
    "name": "3 Day Legend Paddock Club",
    "circuit": "Belgian Grand Prix",
    "location": "Spa-Francorchamps",
    "country": "Belgium",
    "countryCode": "BE",
    "date": "2026-07-19",
    "dateRange": "17 - 19 Jul",
    "price": 11170,
    "currency": "USD",
    "availability": "Enquire",
    "totalCapacity": 50,
    "image": "/images/circuits/spa.jpg",
    "tier": "legend",
    "duration": "3_day",
    "includes": [
      "Paddock Club Access",
      "Premium Dining",
      "Open Bar",
      "Pit Lane Walk",
      "Driver Appearances"
    ],
    "featured": false,
    "raceId": "belgium-2026"
  },
  {
    "id": "belgium-paddock-club-audi-2026",
    "name": "3 Day Paddock Club - Audi",
    "circuit": "Belgian Grand Prix",
    "location": "Spa-Francorchamps",
    "country": "Belgium",
    "countryCode": "BE",
    "date": "2026-07-19",
    "dateRange": "17 - 19 Jul",
    "price": 9499,
    "currency": "USD",
    "availability": "Enquire",
    "totalCapacity": 50,
    "image": "/images/circuits/spa.jpg",
    "tier": "paddock",
    "duration": "3_day",
    "includes": [
      "Paddock Access",
      "Gourmet Dining",
      "Open Bar",
      "Pit Lane Walk"
    ],
    "featured": false,
    "raceId": "belgium-2026"
  },
  {
    "id": "belgium-f1-experiences-paddock-club-2026",
    "name": "3 Day F1 Experiences Paddock Club",
    "circuit": "Belgian Grand Prix",
    "location": "Spa-Francorchamps",
    "country": "Belgium",
    "countryCode": "BE",
    "date": "2026-07-19",
    "dateRange": "17 - 19 Jul",
    "price": 7540,
    "currency": "USD",
    "availability": "Enquire",
    "totalCapacity": 50,
    "image": "/images/circuits/spa.jpg",
    "tier": "paddock",
    "duration": "3_day",
    "includes": [
      "Paddock Access",
      "Gourmet Dining",
      "Open Bar",
      "Pit Lane Walk"
    ],
    "featured": false,
    "raceId": "belgium-2026"
  },
  {
    "id": "belgium-paddock-club-club-suite-2026",
    "name": "3 Day Paddock Club - Club Suite",
    "circuit": "Belgian Grand Prix",
    "location": "Spa-Francorchamps",
    "country": "Belgium",
    "countryCode": "BE",
    "date": "2026-07-19",
    "dateRange": "17 - 19 Jul",
    "price": 6353,
    "currency": "USD",
    "availability": 10,
    "totalCapacity": 30,
    "image": "/images/circuits/spa.jpg",
    "tier": "paddock",
    "duration": "3_day",
    "includes": [
      "Paddock Access",
      "Gourmet Dining",
      "Open Bar",
      "Pit Lane Walk"
    ],
    "featured": false,
    "raceId": "belgium-2026"
  },
  {
    "id": "belgium-champions-club-2026",
    "name": "3 Day Champions Club",
    "circuit": "Belgian Grand Prix",
    "location": "Spa-Francorchamps",
    "country": "Belgium",
    "countryCode": "BE",
    "date": "2026-07-19",
    "dateRange": "17 - 19 Jul",
    "price": 4234,
    "currency": "USD",
    "availability": 10,
    "totalCapacity": 30,
    "image": "/images/circuits/spa.jpg",
    "tier": "champions",
    "duration": "3_day",
    "includes": [
      "Grandstand Seats",
      "Hospitality Suite",
      "Gourmet Lunch",
      "Pit Lane Walk"
    ],
    "featured": false,
    "raceId": "belgium-2026"
  },
  {
    "id": "hungary-legend-paddock-club-2026",
    "name": "3 Day Legend Paddock Club",
    "circuit": "Hungarian Grand Prix",
    "location": "Budapest",
    "country": "Hungary",
    "countryCode": "HU",
    "date": "2026-07-26",
    "dateRange": "24 - 26 Jul",
    "price": 11683,
    "currency": "USD",
    "availability": "Enquire",
    "totalCapacity": 50,
    "image": "/images/circuits/budapest.jpg",
    "tier": "legend",
    "duration": "3_day",
    "includes": [
      "Paddock Club Access",
      "Premium Dining",
      "Open Bar",
      "Pit Lane Walk",
      "Driver Appearances"
    ],
    "featured": false,
    "raceId": "hungary-2026"
  },
  {
    "id": "hungary-paddock-club-audi-2026",
    "name": "3 Day Paddock Club - Audi",
    "circuit": "Hungarian Grand Prix",
    "location": "Budapest",
    "country": "Hungary",
    "countryCode": "HU",
    "date": "2026-07-26",
    "dateRange": "24 - 26 Jul",
    "price": 10899,
    "currency": "USD",
    "availability": "Enquire",
    "totalCapacity": 50,
    "image": "/images/circuits/budapest.jpg",
    "tier": "paddock",
    "duration": "3_day",
    "includes": [
      "Paddock Access",
      "Gourmet Dining",
      "Open Bar",
      "Pit Lane Walk"
    ],
    "featured": false,
    "raceId": "hungary-2026"
  },
  {
    "id": "hungary-f1-experiences-paddock-club-2026",
    "name": "3 Day F1 Experiences Paddock Club",
    "circuit": "Hungarian Grand Prix",
    "location": "Budapest",
    "country": "Hungary",
    "countryCode": "HU",
    "date": "2026-07-26",
    "dateRange": "24 - 26 Jul",
    "price": 7869,
    "currency": "USD",
    "availability": 15,
    "totalCapacity": 30,
    "image": "/images/circuits/budapest.jpg",
    "tier": "paddock",
    "duration": "3_day",
    "includes": [
      "Paddock Access",
      "Gourmet Dining",
      "Open Bar",
      "Pit Lane Walk"
    ],
    "featured": false,
    "raceId": "hungary-2026"
  },
  {
    "id": "hungary-paddock-club-club-suite-f1-2026",
    "name": "3 Day Paddock Club - Club Suite (F1)",
    "circuit": "Hungarian Grand Prix",
    "location": "Budapest",
    "country": "Hungary",
    "countryCode": "HU",
    "date": "2026-07-26",
    "dateRange": "24 - 26 Jul",
    "price": 6668,
    "currency": "USD",
    "availability": 24,
    "totalCapacity": 30,
    "image": "/images/circuits/budapest.jpg",
    "tier": "paddock",
    "duration": "3_day",
    "includes": [
      "Paddock Access",
      "Gourmet Dining",
      "Open Bar",
      "Pit Lane Walk"
    ],
    "featured": false,
    "raceId": "hungary-2026"
  },
  {
    "id": "hungary-champions-club-2026",
    "name": "3 Day Champions Club",
    "circuit": "Hungarian Grand Prix",
    "location": "Budapest",
    "country": "Hungary",
    "countryCode": "HU",
    "date": "2026-07-26",
    "dateRange": "24 - 26 Jul",
    "price": 4599,
    "currency": "USD",
    "availability": 10,
    "totalCapacity": 30,
    "image": "/images/circuits/budapest.jpg",
    "tier": "champions",
    "duration": "3_day",
    "includes": [
      "Grandstand Seats",
      "Hospitality Suite",
      "Gourmet Lunch",
      "Pit Lane Walk"
    ],
    "featured": false,
    "raceId": "hungary-2026"
  },
  {
    "id": "italy-paddock-club-house-44-2026",
    "name": "3 Day Paddock Club - House 44",
    "circuit": "Italian Grand Prix",
    "location": "Monza",
    "country": "Italy",
    "countryCode": "IT",
    "date": "2026-09-06",
    "dateRange": "04 - 06 Sep",
    "price": 16470,
    "currency": "USD",
    "availability": 10,
    "totalCapacity": 30,
    "image": "/images/circuits/monza.jpg",
    "tier": "paddock",
    "duration": "3_day",
    "includes": [
      "Paddock Access",
      "Gourmet Dining",
      "Open Bar",
      "Pit Lane Walk"
    ],
    "featured": false,
    "raceId": "italy-2026"
  },
  {
    "id": "italy-legend-paddock-club-2026",
    "name": "3 Day Legend Paddock Club",
    "circuit": "Italian Grand Prix",
    "location": "Monza",
    "country": "Italy",
    "countryCode": "IT",
    "date": "2026-09-06",
    "dateRange": "04 - 06 Sep",
    "price": 12703,
    "currency": "USD",
    "availability": "Enquire",
    "totalCapacity": 50,
    "image": "/images/circuits/monza.jpg",
    "tier": "legend",
    "duration": "3_day",
    "includes": [
      "Paddock Club Access",
      "Premium Dining",
      "Open Bar",
      "Pit Lane Walk",
      "Driver Appearances"
    ],
    "featured": false,
    "raceId": "italy-2026"
  },
  {
    "id": "italy-paddock-club-audi-2026",
    "name": "3 Day Paddock Club - Audi",
    "circuit": "Italian Grand Prix",
    "location": "Monza",
    "country": "Italy",
    "countryCode": "IT",
    "date": "2026-09-06",
    "dateRange": "04 - 06 Sep",
    "price": 11589,
    "currency": "USD",
    "availability": "Enquire",
    "totalCapacity": 50,
    "image": "/images/circuits/monza.jpg",
    "tier": "paddock",
    "duration": "3_day",
    "includes": [
      "Paddock Access",
      "Gourmet Dining",
      "Open Bar",
      "Pit Lane Walk"
    ],
    "featured": false,
    "raceId": "italy-2026"
  },
  {
    "id": "italy-paddock-club-red-bull-2026",
    "name": "3 Day Paddock Club - Red Bull",
    "circuit": "Italian Grand Prix",
    "location": "Monza",
    "country": "Italy",
    "countryCode": "IT",
    "date": "2026-09-06",
    "dateRange": "04 - 06 Sep",
    "price": 13500,
    "currency": "USD",
    "availability": "Enquire",
    "totalCapacity": 50,
    "image": "/images/circuits/monza.jpg",
    "tier": "paddock",
    "duration": "3_day",
    "includes": [
      "Paddock Access",
      "Gourmet Dining",
      "Open Bar",
      "Pit Lane Walk"
    ],
    "featured": false,
    "raceId": "italy-2026"
  },
  {
    "id": "italy-paddock-club-alpine-team-2026",
    "name": "3 Day Paddock Club - Alpine Team",
    "circuit": "Italian Grand Prix",
    "location": "Monza",
    "country": "Italy",
    "countryCode": "IT",
    "date": "2026-09-06",
    "dateRange": "04 - 06 Sep",
    "price": 10500,
    "currency": "USD",
    "availability": 20,
    "totalCapacity": 30,
    "image": "/images/circuits/monza.jpg",
    "tier": "paddock",
    "duration": "3_day",
    "includes": [
      "Paddock Access",
      "Gourmet Dining",
      "Open Bar",
      "Pit Lane Walk"
    ],
    "featured": false,
    "raceId": "italy-2026"
  },
  {
    "id": "italy-paddock-club-team-haas-2026",
    "name": "3 Day Paddock Club - Team Haas",
    "circuit": "Italian Grand Prix",
    "location": "Monza",
    "country": "Italy",
    "countryCode": "IT",
    "date": "2026-09-06",
    "dateRange": "04 - 06 Sep",
    "price": 11495,
    "currency": "USD",
    "availability": 4,
    "totalCapacity": 30,
    "image": "/images/circuits/monza.jpg",
    "tier": "paddock",
    "duration": "3_day",
    "includes": [
      "Paddock Access",
      "Gourmet Dining",
      "Open Bar",
      "Pit Lane Walk"
    ],
    "featured": false,
    "raceId": "italy-2026"
  },
  {
    "id": "italy-f1-experiences-paddock-club-2026",
    "name": "3 Day F1 Experiences Paddock Club",
    "circuit": "Italian Grand Prix",
    "location": "Monza",
    "country": "Italy",
    "countryCode": "IT",
    "date": "2026-09-06",
    "dateRange": "04 - 06 Sep",
    "price": 8799,
    "currency": "USD",
    "availability": "Enquire",
    "totalCapacity": 50,
    "image": "/images/circuits/monza.jpg",
    "tier": "paddock",
    "duration": "3_day",
    "includes": [
      "Paddock Access",
      "Gourmet Dining",
      "Open Bar",
      "Pit Lane Walk"
    ],
    "featured": false,
    "raceId": "italy-2026"
  },
  {
    "id": "italy-schumacher-lounge-2026",
    "name": "3 Day Schumacher Lounge",
    "circuit": "Italian Grand Prix",
    "location": "Monza",
    "country": "Italy",
    "countryCode": "IT",
    "date": "2026-09-06",
    "dateRange": "04 - 06 Sep",
    "price": 6510,
    "currency": "USD",
    "availability": 10,
    "totalCapacity": 30,
    "image": "/images/circuits/monza.jpg",
    "tier": "hero",
    "duration": "3_day",
    "includes": [
      "Hospitality Access",
      "Race Viewing",
      "Refreshments"
    ],
    "featured": false,
    "raceId": "italy-2026"
  },
  {
    "id": "madrid-gordon-ramsey-f1-garage-2026",
    "name": "3 Day Gordon Ramsey at F1 Garage",
    "circuit": "Madrid Grand Prix",
    "location": "Madrid",
    "country": "Spain",
    "countryCode": "ES",
    "date": "2026-09-13",
    "dateRange": "11 - 13 Sep",
    "price": 30250,
    "currency": "USD",
    "availability": "Enquire",
    "totalCapacity": 50,
    "image": "/images/circuits/madrid.jpg",
    "tier": "hero",
    "duration": "3_day",
    "includes": [
      "Hospitality Access",
      "Race Viewing",
      "Refreshments"
    ],
    "featured": false,
    "raceId": "madrid-2026"
  },
  {
    "id": "madrid-paddock-club-house-44-2026",
    "name": "3 Day Paddock Club - House 44",
    "circuit": "Madrid Grand Prix",
    "location": "Madrid",
    "country": "Spain",
    "countryCode": "ES",
    "date": "2026-09-13",
    "dateRange": "11 - 13 Sep",
    "price": 16355,
    "currency": "USD",
    "availability": "Enquire",
    "totalCapacity": 50,
    "image": "/images/circuits/madrid.jpg",
    "tier": "paddock",
    "duration": "3_day",
    "includes": [
      "Paddock Access",
      "Gourmet Dining",
      "Open Bar",
      "Pit Lane Walk"
    ],
    "featured": false,
    "raceId": "madrid-2026"
  },
  {
    "id": "madrid-paddock-club-team-haas-2026",
    "name": "3 Day Paddock Club - Team Haas",
    "circuit": "Madrid Grand Prix",
    "location": "Madrid",
    "country": "Spain",
    "countryCode": "ES",
    "date": "2026-09-13",
    "dateRange": "11 - 13 Sep",
    "price": 9679,
    "currency": "USD",
    "availability": "Enquire",
    "totalCapacity": 50,
    "image": "/images/circuits/madrid.jpg",
    "tier": "paddock",
    "duration": "3_day",
    "includes": [
      "Paddock Access",
      "Gourmet Dining",
      "Open Bar",
      "Pit Lane Walk"
    ],
    "featured": false,
    "raceId": "madrid-2026"
  },
  {
    "id": "madrid-paddock-club-club-suite-f1-2026",
    "name": "3 Day Paddock Club - Club Suite (F1)",
    "circuit": "Madrid Grand Prix",
    "location": "Madrid",
    "country": "Spain",
    "countryCode": "ES",
    "date": "2026-09-13",
    "dateRange": "11 - 13 Sep",
    "price": 7750,
    "currency": "USD",
    "availability": 31,
    "totalCapacity": 31,
    "image": "/images/circuits/madrid.jpg",
    "tier": "paddock",
    "duration": "3_day",
    "includes": [
      "Paddock Access",
      "Gourmet Dining",
      "Open Bar",
      "Pit Lane Walk"
    ],
    "featured": false,
    "raceId": "madrid-2026"
  },
  {
    "id": "madrid-champions-club-2026",
    "name": "3 Day Champions Club",
    "circuit": "Madrid Grand Prix",
    "location": "Madrid",
    "country": "Spain",
    "countryCode": "ES",
    "date": "2026-09-13",
    "dateRange": "11 - 13 Sep",
    "price": 5500,
    "currency": "USD",
    "availability": "Enquire",
    "totalCapacity": 50,
    "image": "/images/circuits/madrid.jpg",
    "tier": "champions",
    "duration": "3_day",
    "includes": [
      "Grandstand Seats",
      "Hospitality Suite",
      "Gourmet Lunch",
      "Pit Lane Walk"
    ],
    "featured": false,
    "raceId": "madrid-2026"
  },
  {
    "id": "azerbaijan-legend-paddock-club-2026",
    "name": "3 Day Legend Paddock Club",
    "circuit": "Azerbaijan Grand Prix",
    "location": "Baku",
    "country": "Azerbaijan",
    "countryCode": "AZ",
    "date": "2026-09-26",
    "dateRange": "24 - 26 Sep",
    "price": 9800,
    "currency": "USD",
    "availability": 10,
    "totalCapacity": 30,
    "image": "/images/circuits/baku.jpg",
    "tier": "legend",
    "duration": "3_day",
    "includes": [
      "Paddock Club Access",
      "Premium Dining",
      "Open Bar",
      "Pit Lane Walk",
      "Driver Appearances"
    ],
    "featured": false,
    "raceId": "azerbaijan-2026"
  },
  {
    "id": "azerbaijan-f1-experiences-paddock-club-2026",
    "name": "3 Day F1 Experiences Paddock Club",
    "circuit": "Azerbaijan Grand Prix",
    "location": "Baku",
    "country": "Azerbaijan",
    "countryCode": "AZ",
    "date": "2026-09-26",
    "dateRange": "24 - 26 Sep",
    "price": 6699,
    "currency": "USD",
    "availability": 10,
    "totalCapacity": 30,
    "image": "/images/circuits/baku.jpg",
    "tier": "paddock",
    "duration": "3_day",
    "includes": [
      "Paddock Access",
      "Gourmet Dining",
      "Open Bar",
      "Pit Lane Walk"
    ],
    "featured": false,
    "raceId": "azerbaijan-2026"
  },
  {
    "id": "azerbaijan-paddock-club-club-suite-f1-2026",
    "name": "3 Day Paddock Club - Club Suite (F1)",
    "circuit": "Azerbaijan Grand Prix",
    "location": "Baku",
    "country": "Azerbaijan",
    "countryCode": "AZ",
    "date": "2026-09-26",
    "dateRange": "24 - 26 Sep",
    "price": 5500,
    "currency": "USD",
    "availability": 27,
    "totalCapacity": 30,
    "image": "/images/circuits/baku.jpg",
    "tier": "paddock",
    "duration": "3_day",
    "includes": [
      "Paddock Access",
      "Gourmet Dining",
      "Open Bar",
      "Pit Lane Walk"
    ],
    "featured": false,
    "raceId": "azerbaijan-2026"
  },
  {
    "id": "azerbaijan-champions-club-2026",
    "name": "3 Day Champions Club",
    "circuit": "Azerbaijan Grand Prix",
    "location": "Baku",
    "country": "Azerbaijan",
    "countryCode": "AZ",
    "date": "2026-09-26",
    "dateRange": "24 - 26 Sep",
    "price": 3999,
    "currency": "USD",
    "availability": 10,
    "totalCapacity": 30,
    "image": "/images/circuits/baku.jpg",
    "tier": "champions",
    "duration": "3_day",
    "includes": [
      "Grandstand Seats",
      "Hospitality Suite",
      "Gourmet Lunch",
      "Pit Lane Walk"
    ],
    "featured": false,
    "raceId": "azerbaijan-2026"
  },
  {
    "id": "singapore-f1-experiences-paddock-club-enquire-2026",
    "name": "3 Day F1 Experiences Paddock Club",
    "circuit": "Singapore Grand Prix",
    "location": "Marina Bay",
    "country": "Singapore",
    "countryCode": "SG",
    "date": "2026-10-11",
    "dateRange": "09 - 11 Oct",
    "price": 13950,
    "currency": "USD",
    "availability": "Enquire",
    "totalCapacity": 50,
    "image": "/images/circuits/singapore.jpg",
    "tier": "paddock",
    "duration": "3_day",
    "includes": [
      "Paddock Access",
      "Gourmet Dining",
      "Open Bar",
      "Pit Lane Walk"
    ],
    "featured": false,
    "raceId": "singapore-2026"
  },
  {
    "id": "singapore-f1-experiences-paddock-club-15500-2026",
    "name": "3 Day F1 Experiences Paddock Club",
    "circuit": "Singapore Grand Prix",
    "location": "Marina Bay",
    "country": "Singapore",
    "countryCode": "SG",
    "date": "2026-10-11",
    "dateRange": "09 - 11 Oct",
    "price": 15500,
    "currency": "USD",
    "availability": "Enquire",
    "totalCapacity": 50,
    "image": "/images/circuits/singapore.jpg",
    "tier": "paddock",
    "duration": "3_day",
    "includes": [
      "Paddock Access",
      "Gourmet Dining",
      "Open Bar",
      "Pit Lane Walk"
    ],
    "featured": false,
    "raceId": "singapore-2026"
  },
  {
    "id": "singapore-paddock-club-clubhouse-2026",
    "name": "3 Day Paddock Club - Clubhouse",
    "circuit": "Singapore Grand Prix",
    "location": "Marina Bay",
    "country": "Singapore",
    "countryCode": "SG",
    "date": "2026-10-11",
    "dateRange": "09 - 11 Oct",
    "price": 16500,
    "currency": "USD",
    "availability": 6,
    "totalCapacity": 30,
    "image": "/images/circuits/singapore.jpg",
    "tier": "paddock",
    "duration": "3_day",
    "includes": [
      "Paddock Access",
      "Gourmet Dining",
      "Open Bar",
      "Pit Lane Walk"
    ],
    "featured": false,
    "raceId": "singapore-2026"
  },
  {
    "id": "singapore-champions-club-2026",
    "name": "3 Day Champions Club",
    "circuit": "Singapore Grand Prix",
    "location": "Marina Bay",
    "country": "Singapore",
    "countryCode": "SG",
    "date": "2026-10-11",
    "dateRange": "09 - 11 Oct",
    "price": 11150,
    "currency": "USD",
    "availability": "Enquire",
    "totalCapacity": 50,
    "image": "/images/circuits/singapore.jpg",
    "tier": "champions",
    "duration": "3_day",
    "includes": [
      "Grandstand Seats",
      "Hospitality Suite",
      "Gourmet Lunch",
      "Pit Lane Walk"
    ],
    "featured": false,
    "raceId": "singapore-2026"
  },
  {
    "id": "singapore-national-gallery-vip-3days-2026",
    "name": "3 Days National Gallery VIP",
    "circuit": "Singapore Grand Prix",
    "location": "Marina Bay",
    "country": "Singapore",
    "countryCode": "SG",
    "date": "2026-10-11",
    "dateRange": "09 - 11 Oct",
    "price": 6950,
    "currency": "USD",
    "availability": 150,
    "totalCapacity": 150,
    "image": "/images/circuits/singapore.jpg",
    "tier": "hero",
    "duration": "3_day",
    "includes": [
      "Hospitality Access",
      "Race Viewing",
      "Refreshments"
    ],
    "featured": true,
    "raceId": "singapore-2026"
  },
  {
    "id": "singapore-national-gallery-vip-sat-sun-2026",
    "name": "Saturday & Sunday National Gallery VIP",
    "circuit": "Singapore Grand Prix",
    "location": "Marina Bay",
    "country": "Singapore",
    "countryCode": "SG",
    "date": "2026-10-11",
    "dateRange": "09 - 11 Oct",
    "price": 6500,
    "currency": "USD",
    "availability": 150,
    "totalCapacity": 150,
    "image": "/images/circuits/singapore.jpg",
    "tier": "hero",
    "duration": "2_day",
    "includes": [
      "Hospitality Access",
      "Race Viewing",
      "Refreshments"
    ],
    "featured": false,
    "raceId": "singapore-2026"
  },
  {
    "id": "singapore-national-gallery-vip-sunday-2026",
    "name": "Sunday National Gallery VIP",
    "circuit": "Singapore Grand Prix",
    "location": "Marina Bay",
    "country": "Singapore",
    "countryCode": "SG",
    "date": "2026-10-11",
    "dateRange": "09 - 11 Oct",
    "price": 5500,
    "currency": "USD",
    "availability": 150,
    "totalCapacity": 150,
    "image": "/images/circuits/singapore.jpg",
    "tier": "hero",
    "duration": "sunday_only",
    "includes": [
      "Hospitality Access",
      "Race Viewing",
      "Refreshments"
    ],
    "featured": false,
    "raceId": "singapore-2026"
  },
  {
    "id": "singapore-national-gallery-vip-saturday-2026",
    "name": "Saturday National Gallery VIP",
    "circuit": "Singapore Grand Prix",
    "location": "Marina Bay",
    "country": "Singapore",
    "countryCode": "SG",
    "date": "2026-10-11",
    "dateRange": "09 - 11 Oct",
    "price": 2950,
    "currency": "USD",
    "availability": 150,
    "totalCapacity": 150,
    "image": "/images/circuits/singapore.jpg",
    "tier": "hero",
    "duration": "saturday_only",
    "includes": [
      "Hospitality Access",
      "Race Viewing",
      "Refreshments"
    ],
    "featured": false,
    "raceId": "singapore-2026"
  },
  {
    "id": "singapore-national-gallery-vip-friday-2026",
    "name": "Friday National Gallery VIP",
    "circuit": "Singapore Grand Prix",
    "location": "Marina Bay",
    "country": "Singapore",
    "countryCode": "SG",
    "date": "2026-10-11",
    "dateRange": "09 - 11 Oct",
    "price": 950,
    "currency": "USD",
    "availability": 150,
    "totalCapacity": 150,
    "image": "/images/circuits/singapore.jpg",
    "tier": "hero",
    "duration": "friday_only",
    "includes": [
      "Hospitality Access",
      "Race Viewing",
      "Refreshments"
    ],
    "featured": false,
    "raceId": "singapore-2026"
  },
  {
    "id": "usa-gordon-ramsey-f1-paddock-2026",
    "name": "3 Day Gordon Ramsay @ F1 Paddock",
    "circuit": "United States Grand Prix",
    "location": "Austin",
    "country": "United States",
    "countryCode": "US",
    "date": "2026-10-25",
    "dateRange": "23 - 25 Oct",
    "price": 27000,
    "currency": "USD",
    "availability": 10,
    "totalCapacity": 30,
    "image": "/images/circuits/austin.jpg",
    "tier": "paddock",
    "duration": "3_day",
    "includes": [
      "Paddock Access",
      "Gourmet Dining",
      "Open Bar",
      "Pit Lane Walk"
    ],
    "featured": false,
    "raceId": "usa-2026"
  },
  {
    "id": "usa-paddock-club-alpine-team-2026",
    "name": "3 Day Paddock Club - Alpine Team",
    "circuit": "United States Grand Prix",
    "location": "Austin",
    "country": "United States",
    "countryCode": "US",
    "date": "2026-10-25",
    "dateRange": "23 - 25 Oct",
    "price": 13500,
    "currency": "USD",
    "availability": "Enquire",
    "totalCapacity": 50,
    "image": "/images/circuits/austin.jpg",
    "tier": "paddock",
    "duration": "3_day",
    "includes": [
      "Paddock Access",
      "Gourmet Dining",
      "Open Bar",
      "Pit Lane Walk"
    ],
    "featured": false,
    "raceId": "usa-2026"
  },
  {
    "id": "usa-champions-club-trackside-ew-2026",
    "name": "3 Day Champions Club - Trackside E/W",
    "circuit": "United States Grand Prix",
    "location": "Austin",
    "country": "United States",
    "countryCode": "US",
    "date": "2026-10-25",
    "dateRange": "23 - 25 Oct",
    "price": 5700,
    "currency": "USD",
    "availability": 10,
    "totalCapacity": 30,
    "image": "/images/circuits/austin.jpg",
    "tier": "champions",
    "duration": "3_day",
    "includes": [
      "Grandstand Seats",
      "Hospitality Suite",
      "Gourmet Lunch",
      "Pit Lane Walk"
    ],
    "featured": false,
    "raceId": "usa-2026"
  },
  {
    "id": "mexico-legend-f1-experiences-paddock-club-2026",
    "name": "3 Day Legend - F1 Experiences Paddock Club",
    "circuit": "Mexico City Grand Prix",
    "location": "Mexico City",
    "country": "Mexico",
    "countryCode": "MX",
    "date": "2026-11-01",
    "dateRange": "30 Oct - 01 Nov",
    "price": 13899,
    "currency": "USD",
    "availability": "Enquire",
    "totalCapacity": 50,
    "image": "/images/circuits/mexico.jpg",
    "tier": "legend",
    "duration": "3_day",
    "includes": [
      "Paddock Club Access",
      "Premium Dining",
      "Open Bar",
      "Pit Lane Walk",
      "Driver Appearances"
    ],
    "featured": false,
    "raceId": "mexico-2026"
  },
  {
    "id": "mexico-paddock-club-house-44-2026",
    "name": "3 Day Paddock Club - House 44",
    "circuit": "Mexico City Grand Prix",
    "location": "Mexico City",
    "country": "Mexico",
    "countryCode": "MX",
    "date": "2026-11-01",
    "dateRange": "30 Oct - 01 Nov",
    "price": 15000,
    "currency": "USD",
    "availability": 10,
    "totalCapacity": 30,
    "image": "/images/circuits/mexico.jpg",
    "tier": "paddock",
    "duration": "3_day",
    "includes": [
      "Paddock Access",
      "Gourmet Dining",
      "Open Bar",
      "Pit Lane Walk"
    ],
    "featured": false,
    "raceId": "mexico-2026"
  },
  {
    "id": "mexico-legend-paddock-club-2026",
    "name": "3 Day Legend Paddock Club",
    "circuit": "Mexico City Grand Prix",
    "location": "Mexico City",
    "country": "Mexico",
    "countryCode": "MX",
    "date": "2026-11-01",
    "dateRange": "30 Oct - 01 Nov",
    "price": 12800,
    "currency": "USD",
    "availability": "Enquire",
    "totalCapacity": 50,
    "image": "/images/circuits/mexico.jpg",
    "tier": "legend",
    "duration": "3_day",
    "includes": [
      "Paddock Club Access",
      "Premium Dining",
      "Open Bar",
      "Pit Lane Walk",
      "Driver Appearances"
    ],
    "featured": false,
    "raceId": "mexico-2026"
  },
  {
    "id": "mexico-paddock-club-team-haas-2026",
    "name": "3 Day Paddock Club - Team Haas",
    "circuit": "Mexico City Grand Prix",
    "location": "Mexico City",
    "country": "Mexico",
    "countryCode": "MX",
    "date": "2026-11-01",
    "dateRange": "30 Oct - 01 Nov",
    "price": 11899,
    "currency": "USD",
    "availability": 10,
    "totalCapacity": 30,
    "image": "/images/circuits/mexico.jpg",
    "tier": "paddock",
    "duration": "3_day",
    "includes": [
      "Paddock Access",
      "Gourmet Dining",
      "Open Bar",
      "Pit Lane Walk"
    ],
    "featured": false,
    "raceId": "mexico-2026"
  },
  {
    "id": "mexico-f1-experiences-paddock-club-2026",
    "name": "3 Day F1 Experiences Paddock Club",
    "circuit": "Mexico City Grand Prix",
    "location": "Mexico City",
    "country": "Mexico",
    "countryCode": "MX",
    "date": "2026-11-01",
    "dateRange": "30 Oct - 01 Nov",
    "price": 9600,
    "currency": "USD",
    "availability": "Enquire",
    "totalCapacity": 50,
    "image": "/images/circuits/mexico.jpg",
    "tier": "paddock",
    "duration": "3_day",
    "includes": [
      "Paddock Access",
      "Gourmet Dining",
      "Open Bar",
      "Pit Lane Walk"
    ],
    "featured": false,
    "raceId": "mexico-2026"
  },
  {
    "id": "mexico-champions-club-main-2-2026",
    "name": "3 Day Champions Club - Main 2",
    "circuit": "Mexico City Grand Prix",
    "location": "Mexico City",
    "country": "Mexico",
    "countryCode": "MX",
    "date": "2026-11-01",
    "dateRange": "30 Oct - 01 Nov",
    "price": 5599,
    "currency": "USD",
    "availability": "Enquire",
    "totalCapacity": 50,
    "image": "/images/circuits/mexico.jpg",
    "tier": "champions",
    "duration": "3_day",
    "includes": [
      "Grandstand Seats",
      "Hospitality Suite",
      "Gourmet Lunch",
      "Pit Lane Walk"
    ],
    "featured": false,
    "raceId": "mexico-2026"
  },
  {
    "id": "brazil-legend-paddock-club-2026",
    "name": "3 Day Legend Paddock Club",
    "circuit": "São Paulo Grand Prix",
    "location": "São Paulo",
    "country": "Brazil",
    "countryCode": "BR",
    "date": "2026-11-08",
    "dateRange": "06 - 08 Nov",
    "price": 10799,
    "currency": "USD",
    "availability": "Enquire",
    "totalCapacity": 50,
    "image": "/images/circuits/interlagos.jpg",
    "tier": "legend",
    "duration": "3_day",
    "includes": [
      "Paddock Club Access",
      "Premium Dining",
      "Open Bar",
      "Pit Lane Walk",
      "Driver Appearances"
    ],
    "featured": false,
    "raceId": "brazil-2026"
  },
  {
    "id": "brazil-paddock-club-red-bull-2026",
    "name": "3 Day Paddock Club - Red Bull",
    "circuit": "São Paulo Grand Prix",
    "location": "São Paulo",
    "country": "Brazil",
    "countryCode": "BR",
    "date": "2026-11-08",
    "dateRange": "06 - 08 Nov",
    "price": 10299,
    "currency": "USD",
    "availability": "Enquire",
    "totalCapacity": 50,
    "image": "/images/circuits/interlagos.jpg",
    "tier": "paddock",
    "duration": "3_day",
    "includes": [
      "Paddock Access",
      "Gourmet Dining",
      "Open Bar",
      "Pit Lane Walk"
    ],
    "featured": false,
    "raceId": "brazil-2026"
  },
  {
    "id": "brazil-f1-experiences-paddock-club-2026",
    "name": "3 Day F1 Experiences Paddock Club",
    "circuit": "São Paulo Grand Prix",
    "location": "São Paulo",
    "country": "Brazil",
    "countryCode": "BR",
    "date": "2026-11-08",
    "dateRange": "06 - 08 Nov",
    "price": 7999,
    "currency": "USD",
    "availability": "Enquire",
    "totalCapacity": 50,
    "image": "/images/circuits/interlagos.jpg",
    "tier": "paddock",
    "duration": "3_day",
    "includes": [
      "Paddock Access",
      "Gourmet Dining",
      "Open Bar",
      "Pit Lane Walk"
    ],
    "featured": false,
    "raceId": "brazil-2026"
  },
  {
    "id": "brazil-paddock-club-club-suite-2026",
    "name": "3 Day Paddock Club - Club Suite",
    "circuit": "São Paulo Grand Prix",
    "location": "São Paulo",
    "country": "Brazil",
    "countryCode": "BR",
    "date": "2026-11-08",
    "dateRange": "06 - 08 Nov",
    "price": 7000,
    "currency": "USD",
    "availability": "Enquire",
    "totalCapacity": 50,
    "image": "/images/circuits/interlagos.jpg",
    "tier": "paddock",
    "duration": "3_day",
    "includes": [
      "Paddock Access",
      "Gourmet Dining",
      "Open Bar",
      "Pit Lane Walk"
    ],
    "featured": false,
    "raceId": "brazil-2026"
  },
  {
    "id": "brazil-f1-experiences-lounge-2026",
    "name": "3 Day F1 Experiences Lounge",
    "circuit": "São Paulo Grand Prix",
    "location": "São Paulo",
    "country": "Brazil",
    "countryCode": "BR",
    "date": "2026-11-08",
    "dateRange": "06 - 08 Nov",
    "price": 5999,
    "currency": "USD",
    "availability": 10,
    "totalCapacity": 30,
    "image": "/images/circuits/interlagos.jpg",
    "tier": "paddock",
    "duration": "3_day",
    "includes": [
      "Paddock Access",
      "Gourmet Dining",
      "Open Bar",
      "Pit Lane Walk"
    ],
    "featured": false,
    "raceId": "brazil-2026"
  },
  {
    "id": "brazil-champions-club-2026",
    "name": "3 Day Champions Club",
    "circuit": "São Paulo Grand Prix",
    "location": "São Paulo",
    "country": "Brazil",
    "countryCode": "BR",
    "date": "2026-11-08",
    "dateRange": "06 - 08 Nov",
    "price": 4299,
    "currency": "USD",
    "availability": "Enquire",
    "totalCapacity": 50,
    "image": "/images/circuits/interlagos.jpg",
    "tier": "champions",
    "duration": "3_day",
    "includes": [
      "Grandstand Seats",
      "Hospitality Suite",
      "Gourmet Lunch",
      "Pit Lane Walk"
    ],
    "featured": false,
    "raceId": "brazil-2026"
  },
  {
    "id": "vegas-gordon-ramsey-f1-garage-2026",
    "name": "3 Day Gordon Ramsay - F1 Garage",
    "circuit": "Las Vegas Grand Prix",
    "location": "Las Vegas",
    "country": "United States",
    "countryCode": "US",
    "date": "2026-11-21",
    "dateRange": "19 - 21 Nov",
    "price": 28000,
    "currency": "USD",
    "availability": 10,
    "totalCapacity": 30,
    "image": "/images/circuits/vegas.jpg",
    "tier": "hero",
    "duration": "3_day",
    "includes": [
      "Hospitality Access",
      "Race Viewing",
      "Refreshments"
    ],
    "featured": false,
    "raceId": "vegas-2026"
  },
  {
    "id": "vegas-paddock-club-house-44-2026",
    "name": "3 Day Paddock Club - House 44",
    "circuit": "Las Vegas Grand Prix",
    "location": "Las Vegas",
    "country": "United States",
    "countryCode": "US",
    "date": "2026-11-21",
    "dateRange": "19 - 21 Nov",
    "price": 18530,
    "currency": "USD",
    "availability": 10,
    "totalCapacity": 30,
    "image": "/images/circuits/vegas.jpg",
    "tier": "paddock",
    "duration": "3_day",
    "includes": [
      "Paddock Access",
      "Gourmet Dining",
      "Open Bar",
      "Pit Lane Walk"
    ],
    "featured": false,
    "raceId": "vegas-2026"
  },
  {
    "id": "qatar-gordon-ramsey-f1-garage-2026",
    "name": "3 Day Gordon Ramsey at F1 Garage",
    "circuit": "Qatar Grand Prix",
    "location": "Lusail",
    "country": "Qatar",
    "countryCode": "QA",
    "date": "2026-11-29",
    "dateRange": "27 - 29 Nov",
    "price": 30000,
    "currency": "USD",
    "availability": "Enquire",
    "totalCapacity": 50,
    "image": "/images/circuits/lusail.jpg",
    "tier": "hero",
    "duration": "3_day",
    "includes": [
      "Hospitality Access",
      "Race Viewing",
      "Refreshments"
    ],
    "featured": false,
    "raceId": "qatar-2026"
  },
  {
    "id": "qatar-legend-paddock-club-2026",
    "name": "3 Day Legend Paddock Club",
    "circuit": "Qatar Grand Prix",
    "location": "Lusail",
    "country": "Qatar",
    "countryCode": "QA",
    "date": "2026-11-29",
    "dateRange": "27 - 29 Nov",
    "price": 12499,
    "currency": "USD",
    "availability": 25,
    "totalCapacity": 30,
    "image": "/images/circuits/lusail.jpg",
    "tier": "legend",
    "duration": "3_day",
    "includes": [
      "Paddock Club Access",
      "Premium Dining",
      "Open Bar",
      "Pit Lane Walk",
      "Driver Appearances"
    ],
    "featured": false,
    "raceId": "qatar-2026"
  },
  {
    "id": "qatar-paddock-club-audi-2026",
    "name": "3 Day Paddock Club - Audi",
    "circuit": "Qatar Grand Prix",
    "location": "Lusail",
    "country": "Qatar",
    "countryCode": "QA",
    "date": "2026-11-29",
    "dateRange": "27 - 29 Nov",
    "price": 11599,
    "currency": "USD",
    "availability": "Enquire",
    "totalCapacity": 50,
    "image": "/images/circuits/lusail.jpg",
    "tier": "paddock",
    "duration": "3_day",
    "includes": [
      "Paddock Access",
      "Gourmet Dining",
      "Open Bar",
      "Pit Lane Walk"
    ],
    "featured": false,
    "raceId": "qatar-2026"
  },
  {
    "id": "qatar-paddock-club-red-bull-2026",
    "name": "3 Day Paddock Club - Red Bull",
    "circuit": "Qatar Grand Prix",
    "location": "Lusail",
    "country": "Qatar",
    "countryCode": "QA",
    "date": "2026-11-29",
    "dateRange": "27 - 29 Nov",
    "price": 11799,
    "currency": "USD",
    "availability": 8,
    "totalCapacity": 30,
    "image": "/images/circuits/lusail.jpg",
    "tier": "paddock",
    "duration": "3_day",
    "includes": [
      "Paddock Access",
      "Gourmet Dining",
      "Open Bar",
      "Pit Lane Walk"
    ],
    "featured": false,
    "raceId": "qatar-2026"
  },
  {
    "id": "qatar-paddock-club-team-haas-2026",
    "name": "3 Day Paddock Club - Team Haas",
    "circuit": "Qatar Grand Prix",
    "location": "Lusail",
    "country": "Qatar",
    "countryCode": "QA",
    "date": "2026-11-29",
    "dateRange": "27 - 29 Nov",
    "price": 10399,
    "currency": "USD",
    "availability": 10,
    "totalCapacity": 30,
    "image": "/images/circuits/lusail.jpg",
    "tier": "paddock",
    "duration": "3_day",
    "includes": [
      "Paddock Access",
      "Gourmet Dining",
      "Open Bar",
      "Pit Lane Walk"
    ],
    "featured": false,
    "raceId": "qatar-2026"
  },
  {
    "id": "qatar-f1-experiences-paddock-club-2026",
    "name": "3 Day F1 Experiences Paddock Club",
    "circuit": "Qatar Grand Prix",
    "location": "Lusail",
    "country": "Qatar",
    "countryCode": "QA",
    "date": "2026-11-29",
    "dateRange": "27 - 29 Nov",
    "price": 9578,
    "currency": "USD",
    "availability": 10,
    "totalCapacity": 30,
    "image": "/images/circuits/lusail.jpg",
    "tier": "paddock",
    "duration": "3_day",
    "includes": [
      "Paddock Access",
      "Gourmet Dining",
      "Open Bar",
      "Pit Lane Walk"
    ],
    "featured": false,
    "raceId": "qatar-2026"
  },
  {
    "id": "qatar-paddock-club-3-nights-hotel-2026",
    "name": "3 Day Paddock Club & 3 Nights in a 5* Hotel",
    "circuit": "Qatar Grand Prix",
    "location": "Lusail",
    "country": "Qatar",
    "countryCode": "QA",
    "date": "2026-11-29",
    "dateRange": "27 - 29 Nov",
    "price": 21000,
    "currency": "USD",
    "availability": 14,
    "totalCapacity": 30,
    "image": "/images/circuits/lusail.jpg",
    "tier": "paddock",
    "duration": "3_day",
    "includes": [
      "Paddock Access",
      "Gourmet Dining",
      "Open Bar",
      "Pit Lane Walk"
    ],
    "featured": false,
    "raceId": "qatar-2026"
  },
  {
    "id": "qatar-champions-club-2026",
    "name": "3 Day Champions Club",
    "circuit": "Qatar Grand Prix",
    "location": "Lusail",
    "country": "Qatar",
    "countryCode": "QA",
    "date": "2026-11-29",
    "dateRange": "27 - 29 Nov",
    "price": 5299,
    "currency": "USD",
    "availability": 10,
    "totalCapacity": 30,
    "image": "/images/circuits/lusail.jpg",
    "tier": "champions",
    "duration": "3_day",
    "includes": [
      "Grandstand Seats",
      "Hospitality Suite",
      "Gourmet Lunch",
      "Pit Lane Walk"
    ],
    "featured": false,
    "raceId": "qatar-2026"
  },
  {
    "id": "abudhabi-paddock-club-house-44-2026",
    "name": "3 Day Paddock Club - House 44",
    "circuit": "Abu Dhabi Grand Prix",
    "location": "Yas Marina",
    "country": "UAE",
    "countryCode": "AE",
    "date": "2026-12-06",
    "dateRange": "04 - 06 Dec",
    "price": 19500,
    "currency": "USD",
    "availability": 26,
    "totalCapacity": 30,
    "image": "/images/circuits/abudhabi.jpg",
    "tier": "paddock",
    "duration": "3_day",
    "includes": [
      "Paddock Access",
      "Gourmet Dining",
      "Open Bar",
      "Pit Lane Walk"
    ],
    "featured": false,
    "raceId": "abudhabi-2026"
  },
  {
    "id": "abudhabi-legend-paddock-club-2026",
    "name": "3 Day Legend Paddock Club",
    "circuit": "Abu Dhabi Grand Prix",
    "location": "Yas Marina",
    "country": "UAE",
    "countryCode": "AE",
    "date": "2026-12-06",
    "dateRange": "04 - 06 Dec",
    "price": 16650,
    "currency": "USD",
    "availability": 8,
    "totalCapacity": 30,
    "image": "/images/circuits/abudhabi.jpg",
    "tier": "legend",
    "duration": "3_day",
    "includes": [
      "Paddock Club Access",
      "Premium Dining",
      "Open Bar",
      "Pit Lane Walk",
      "Driver Appearances"
    ],
    "featured": false,
    "raceId": "abudhabi-2026"
  },
  {
    "id": "abudhabi-paddock-club-red-bull-2026",
    "name": "3 Day Paddock Club - Red Bull",
    "circuit": "Abu Dhabi Grand Prix",
    "location": "Yas Marina",
    "country": "UAE",
    "countryCode": "AE",
    "date": "2026-12-06",
    "dateRange": "04 - 06 Dec",
    "price": 15500,
    "currency": "USD",
    "availability": "Enquire",
    "totalCapacity": 50,
    "image": "/images/circuits/abudhabi.jpg",
    "tier": "paddock",
    "duration": "3_day",
    "includes": [
      "Paddock Access",
      "Gourmet Dining",
      "Open Bar",
      "Pit Lane Walk"
    ],
    "featured": false,
    "raceId": "abudhabi-2026"
  },
  {
    "id": "abudhabi-paddock-club-alpine-team-2026",
    "name": "3 Day Paddock Club - Alpine Team",
    "circuit": "Abu Dhabi Grand Prix",
    "location": "Yas Marina",
    "country": "UAE",
    "countryCode": "AE",
    "date": "2026-12-06",
    "dateRange": "04 - 06 Dec",
    "price": 14995,
    "currency": "USD",
    "availability": 3,
    "totalCapacity": 30,
    "image": "/images/circuits/abudhabi.jpg",
    "tier": "paddock",
    "duration": "3_day",
    "includes": [
      "Paddock Access",
      "Gourmet Dining",
      "Open Bar",
      "Pit Lane Walk"
    ],
    "featured": false,
    "raceId": "abudhabi-2026"
  },
  {
    "id": "abudhabi-f1-experiences-paddock-club-2026",
    "name": "3 Day F1 Experiences Paddock Club",
    "circuit": "Abu Dhabi Grand Prix",
    "location": "Yas Marina",
    "country": "UAE",
    "countryCode": "AE",
    "date": "2026-12-06",
    "dateRange": "04 - 06 Dec",
    "price": 12699,
    "currency": "USD",
    "availability": 6,
    "totalCapacity": 30,
    "image": "/images/circuits/abudhabi.jpg",
    "tier": "paddock",
    "duration": "3_day",
    "includes": [
      "Paddock Access",
      "Gourmet Dining",
      "Open Bar",
      "Pit Lane Walk"
    ],
    "featured": false,
    "raceId": "abudhabi-2026"
  },
  {
    "id": "abudhabi-paddock-club-team-haas-2026",
    "name": "3 Day Paddock Club - Team Haas",
    "circuit": "Abu Dhabi Grand Prix",
    "location": "Yas Marina",
    "country": "UAE",
    "countryCode": "AE",
    "date": "2026-12-06",
    "dateRange": "04 - 06 Dec",
    "price": 14995,
    "currency": "USD",
    "availability": 14,
    "totalCapacity": 30,
    "image": "/images/circuits/abudhabi.jpg",
    "tier": "paddock",
    "duration": "3_day",
    "includes": [
      "Paddock Access",
      "Gourmet Dining",
      "Open Bar",
      "Pit Lane Walk"
    ],
    "featured": false,
    "raceId": "abudhabi-2026"
  },
  {
    "id": "abudhabi-paddock-club-f1-experiences-2026",
    "name": "3 Day Paddock Club - F1 Experiences",
    "circuit": "Abu Dhabi Grand Prix",
    "location": "Yas Marina",
    "country": "UAE",
    "countryCode": "AE",
    "date": "2026-12-06",
    "dateRange": "04 - 06 Dec",
    "price": 13999,
    "currency": "USD",
    "availability": 11,
    "totalCapacity": 30,
    "image": "/images/circuits/abudhabi.jpg",
    "tier": "paddock",
    "duration": "3_day",
    "includes": [
      "Paddock Access",
      "Gourmet Dining",
      "Open Bar",
      "Pit Lane Walk"
    ],
    "featured": false,
    "raceId": "abudhabi-2026"
  },
  {
    "id": "abudhabi-champions-club-2026",
    "name": "3 Day Champions Club",
    "circuit": "Abu Dhabi Grand Prix",
    "location": "Yas Marina",
    "country": "UAE",
    "countryCode": "AE",
    "date": "2026-12-06",
    "dateRange": "04 - 06 Dec",
    "price": 6139,
    "currency": "USD",
    "availability": 30,
    "totalCapacity": 30,
    "image": "/images/circuits/abudhabi.jpg",
    "tier": "champions",
    "duration": "3_day",
    "includes": [
      "Grandstand Seats",
      "Hospitality Suite",
      "Gourmet Lunch",
      "Pit Lane Walk"
    ],
    "featured": false,
    "raceId": "abudhabi-2026"
  },
  {
    "id": "abudhabi-f1-experiences-lounge-main-2026",
    "name": "3 Day F1 Experiences Lounge - Main Straight",
    "circuit": "Abu Dhabi Grand Prix",
    "location": "Yas Marina",
    "country": "UAE",
    "countryCode": "AE",
    "date": "2026-12-06",
    "dateRange": "04 - 06 Dec",
    "price": 6719,
    "currency": "USD",
    "availability": 30,
    "totalCapacity": 30,
    "image": "/images/circuits/abudhabi.jpg",
    "tier": "paddock",
    "duration": "3_day",
    "includes": [
      "Paddock Access",
      "Gourmet Dining",
      "Open Bar",
      "Pit Lane Walk"
    ],
    "featured": false,
    "raceId": "abudhabi-2026"
  },
  {
    "id": "abudhabi-trackside-superyacht-3days-2026",
    "name": "3 Days Trackside Superyacht Hospitality",
    "circuit": "Abu Dhabi Grand Prix",
    "location": "Yas Marina",
    "country": "UAE",
    "countryCode": "AE",
    "date": "2026-12-06",
    "dateRange": "04 - 06 Dec",
    "price": 5950,
    "currency": "USD",
    "availability": 100,
    "totalCapacity": 100,
    "image": "/images/circuits/abudhabi.jpg",
    "tier": "hero",
    "duration": "3_day",
    "includes": [
      "Hospitality Access",
      "Race Viewing",
      "Refreshments"
    ],
    "featured": false,
    "raceId": "abudhabi-2026"
  },
  {
    "id": "abudhabi-club-58-2026",
    "name": "3 Day Club 58",
    "circuit": "Abu Dhabi Grand Prix",
    "location": "Yas Marina",
    "country": "UAE",
    "countryCode": "AE",
    "date": "2026-12-06",
    "dateRange": "04 - 06 Dec",
    "price": 4050,
    "currency": "USD",
    "availability": 30,
    "totalCapacity": 30,
    "image": "/images/circuits/abudhabi.jpg",
    "tier": "hero",
    "duration": "3_day",
    "includes": [
      "Hospitality Access",
      "Race Viewing",
      "Refreshments"
    ],
    "featured": false,
    "raceId": "abudhabi-2026"
  },
  {
    "id": "abudhabi-marina-views-brunch-2026",
    "name": "3 Day Marina Views Brunch",
    "circuit": "Abu Dhabi Grand Prix",
    "location": "Yas Marina",
    "country": "UAE",
    "countryCode": "AE",
    "date": "2026-12-06",
    "dateRange": "04 - 06 Dec",
    "price": 2850,
    "currency": "USD",
    "availability": 40,
    "totalCapacity": 40,
    "image": "/images/circuits/abudhabi.jpg",
    "tier": "hero",
    "duration": "3_day",
    "includes": [
      "Hospitality Access",
      "Race Viewing",
      "Refreshments"
    ],
    "featured": false,
    "raceId": "abudhabi-2026"
  },
  {
    "id": "abudhabi-sunset-lounge-2026",
    "name": "3 Day Sunset Lounge",
    "circuit": "Abu Dhabi Grand Prix",
    "location": "Yas Marina",
    "country": "UAE",
    "countryCode": "AE",
    "date": "2026-12-06",
    "dateRange": "04 - 06 Dec",
    "price": 3250,
    "currency": "USD",
    "availability": 0,
    "totalCapacity": 30,
    "image": "/images/circuits/abudhabi.jpg",
    "tier": "hero",
    "duration": "3_day",
    "includes": [
      "Hospitality Access",
      "Race Viewing",
      "Refreshments"
    ],
    "featured": false,
    "raceId": "abudhabi-2026"
  },
  {
    "id": "abudhabi-skybridge-terrace-3days-2026",
    "name": "3 Days Skybridge Terrace",
    "circuit": "Abu Dhabi Grand Prix",
    "location": "Yas Marina",
    "country": "UAE",
    "countryCode": "AE",
    "date": "2026-12-06",
    "dateRange": "04 - 06 Dec",
    "price": 5500,
    "currency": "USD",
    "availability": 419,
    "totalCapacity": 419,
    "image": "/images/circuits/abudhabi.jpg",
    "tier": "hero",
    "duration": "3_day",
    "includes": [
      "Hospitality Access",
      "Race Viewing",
      "Refreshments"
    ],
    "featured": false,
    "raceId": "abudhabi-2026"
  },
  {
    "id": "abudhabi-skybridge-terrace-sat-sun-2026",
    "name": "Saturday & Sunday Skybridge Terrace",
    "circuit": "Abu Dhabi Grand Prix",
    "location": "Yas Marina",
    "country": "UAE",
    "countryCode": "AE",
    "date": "2026-12-06",
    "dateRange": "04 - 06 Dec",
    "price": 4950,
    "currency": "USD",
    "availability": 419,
    "totalCapacity": 419,
    "image": "/images/circuits/abudhabi.jpg",
    "tier": "hero",
    "duration": "2_day",
    "includes": [
      "Hospitality Access",
      "Race Viewing",
      "Refreshments"
    ],
    "featured": false,
    "raceId": "abudhabi-2026"
  },
  {
    "id": "abudhabi-skybridge-terrace-sunday-2026",
    "name": "Sunday Skybridge Terrace",
    "circuit": "Abu Dhabi Grand Prix",
    "location": "Yas Marina",
    "country": "UAE",
    "countryCode": "AE",
    "date": "2026-12-06",
    "dateRange": "04 - 06 Dec",
    "price": 3500,
    "currency": "USD",
    "availability": 419,
    "totalCapacity": 419,
    "image": "/images/circuits/abudhabi.jpg",
    "tier": "hero",
    "duration": "sunday_only",
    "includes": [
      "Hospitality Access",
      "Race Viewing",
      "Refreshments"
    ],
    "featured": false,
    "raceId": "abudhabi-2026"
  },
  {
    "id": "abudhabi-skybridge-terrace-saturday-2026",
    "name": "Saturday Skybridge Terrace",
    "circuit": "Abu Dhabi Grand Prix",
    "location": "Yas Marina",
    "country": "UAE",
    "countryCode": "AE",
    "date": "2026-12-06",
    "dateRange": "04 - 06 Dec",
    "price": 2250,
    "currency": "USD",
    "availability": 419,
    "totalCapacity": 419,
    "image": "/images/circuits/abudhabi.jpg",
    "tier": "hero",
    "duration": "saturday_only",
    "includes": [
      "Hospitality Access",
      "Race Viewing",
      "Refreshments"
    ],
    "featured": false,
    "raceId": "abudhabi-2026"
  },
  {
    "id": "abudhabi-skybridge-terrace-friday-2026",
    "name": "Friday Skybridge Terrace",
    "circuit": "Abu Dhabi Grand Prix",
    "location": "Yas Marina",
    "country": "UAE",
    "countryCode": "AE",
    "date": "2026-12-06",
    "dateRange": "04 - 06 Dec",
    "price": 495,
    "currency": "USD",
    "availability": 419,
    "totalCapacity": 419,
    "image": "/images/circuits/abudhabi.jpg",
    "tier": "hero",
    "duration": "friday_only",
    "includes": [
      "Hospitality Access",
      "Race Viewing",
      "Refreshments"
    ],
    "featured": false,
    "raceId": "abudhabi-2026"
  },
  {
    "id": "abudhabi-marsa-box-3days-2026",
    "name": "3 Days Marsa Box by ZK",
    "circuit": "Abu Dhabi Grand Prix",
    "location": "Yas Marina",
    "country": "UAE",
    "countryCode": "AE",
    "date": "2026-12-06",
    "dateRange": "04 - 06 Dec",
    "price": 4250,
    "currency": "USD",
    "availability": 195,
    "totalCapacity": 195,
    "image": "/images/circuits/abudhabi.jpg",
    "tier": "hero",
    "duration": "3_day",
    "includes": [
      "Hospitality Access",
      "Race Viewing",
      "Refreshments"
    ],
    "featured": true,
    "raceId": "abudhabi-2026"
  },
  {
    "id": "abudhabi-marsa-box-sat-sun-2026",
    "name": "Saturday & Sunday Marsa Box by ZK",
    "circuit": "Abu Dhabi Grand Prix",
    "location": "Yas Marina",
    "country": "UAE",
    "countryCode": "AE",
    "date": "2026-12-06",
    "dateRange": "04 - 06 Dec",
    "price": 3950,
    "currency": "USD",
    "availability": 195,
    "totalCapacity": 195,
    "image": "/images/circuits/abudhabi.jpg",
    "tier": "hero",
    "duration": "2_day",
    "includes": [
      "Hospitality Access",
      "Race Viewing",
      "Refreshments"
    ],
    "featured": false,
    "raceId": "abudhabi-2026"
  },
  {
    "id": "abudhabi-marsa-box-sunday-2026",
    "name": "Sunday Marsa Box by ZK",
    "circuit": "Abu Dhabi Grand Prix",
    "location": "Yas Marina",
    "country": "UAE",
    "countryCode": "AE",
    "date": "2026-12-06",
    "dateRange": "04 - 06 Dec",
    "price": 2950,
    "currency": "USD",
    "availability": 195,
    "totalCapacity": 195,
    "image": "/images/circuits/abudhabi.jpg",
    "tier": "hero",
    "duration": "sunday_only",
    "includes": [
      "Hospitality Access",
      "Race Viewing",
      "Refreshments"
    ],
    "featured": false,
    "raceId": "abudhabi-2026"
  },
  {
    "id": "abudhabi-marsa-box-saturday-2026",
    "name": "Saturday Marsa Box by ZK",
    "circuit": "Abu Dhabi Grand Prix",
    "location": "Yas Marina",
    "country": "UAE",
    "countryCode": "AE",
    "date": "2026-12-06",
    "dateRange": "04 - 06 Dec",
    "price": 1950,
    "currency": "USD",
    "availability": 197,
    "totalCapacity": 197,
    "image": "/images/circuits/abudhabi.jpg",
    "tier": "hero",
    "duration": "saturday_only",
    "includes": [
      "Hospitality Access",
      "Race Viewing",
      "Refreshments"
    ],
    "featured": false,
    "raceId": "abudhabi-2026"
  },
  {
    "id": "abudhabi-marsa-box-friday-2026",
    "name": "Friday Marsa Box by ZK",
    "circuit": "Abu Dhabi Grand Prix",
    "location": "Yas Marina",
    "country": "UAE",
    "countryCode": "AE",
    "date": "2026-12-06",
    "dateRange": "04 - 06 Dec",
    "price": 495,
    "currency": "USD",
    "availability": 196,
    "totalCapacity": 196,
    "image": "/images/circuits/abudhabi.jpg",
    "tier": "hero",
    "duration": "friday_only",
    "includes": [
      "Hospitality Access",
      "Race Viewing",
      "Refreshments"
    ],
    "featured": false,
    "raceId": "abudhabi-2026"
  },
  {
    "id": "abudhabi-trackside-lounge-3days-2026",
    "name": "3 Days Trackside Lounge",
    "circuit": "Abu Dhabi Grand Prix",
    "location": "Yas Marina",
    "country": "UAE",
    "countryCode": "AE",
    "date": "2026-12-06",
    "dateRange": "04 - 06 Dec",
    "price": 4250,
    "currency": "USD",
    "availability": 80,
    "totalCapacity": 80,
    "image": "/images/circuits/abudhabi.jpg",
    "tier": "hero",
    "duration": "3_day",
    "includes": [
      "Hospitality Access",
      "Race Viewing",
      "Refreshments"
    ],
    "featured": false,
    "raceId": "abudhabi-2026"
  },
  {
    "id": "abudhabi-west-grandstand-2026",
    "name": "3 Day West Grandstand",
    "circuit": "Abu Dhabi Grand Prix",
    "location": "Yas Marina",
    "country": "UAE",
    "countryCode": "AE",
    "date": "2026-12-06",
    "dateRange": "04 - 06 Dec",
    "price": 1350,
    "currency": "USD",
    "availability": "Enquire",
    "totalCapacity": 50,
    "image": "/images/circuits/abudhabi.jpg",
    "tier": "hero",
    "duration": "3_day",
    "includes": [
      "Hospitality Access",
      "Race Viewing",
      "Refreshments"
    ],
    "featured": false,
    "raceId": "abudhabi-2026"
  },
  {
    "id": "abudhabi-south-grandstand-2026",
    "name": "3 Day South Grandstand",
    "circuit": "Abu Dhabi Grand Prix",
    "location": "Yas Marina",
    "country": "UAE",
    "countryCode": "AE",
    "date": "2026-12-06",
    "dateRange": "04 - 06 Dec",
    "price": 1350,
    "currency": "USD",
    "availability": "Enquire",
    "totalCapacity": 50,
    "image": "/images/circuits/abudhabi.jpg",
    "tier": "hero",
    "duration": "3_day",
    "includes": [
      "Hospitality Access",
      "Race Viewing",
      "Refreshments"
    ],
    "featured": false,
    "raceId": "abudhabi-2026"
  },
  {
    "id": "abudhabi-north-grandstand-2026",
    "name": "3 Day North Grandstand",
    "circuit": "Abu Dhabi Grand Prix",
    "location": "Yas Marina",
    "country": "UAE",
    "countryCode": "AE",
    "date": "2026-12-06",
    "dateRange": "04 - 06 Dec",
    "price": 1498,
    "currency": "USD",
    "availability": "Enquire",
    "totalCapacity": 50,
    "image": "/images/circuits/abudhabi.jpg",
    "tier": "hero",
    "duration": "3_day",
    "includes": [
      "Hospitality Access",
      "Race Viewing",
      "Refreshments"
    ],
    "featured": false,
    "raceId": "abudhabi-2026"
  },
  {
    "id": "abudhabi-marina-grandstand-2026",
    "name": "3 Day Marina Grandstand",
    "circuit": "Abu Dhabi Grand Prix",
    "location": "Yas Marina",
    "country": "UAE",
    "countryCode": "AE",
    "date": "2026-12-06",
    "dateRange": "04 - 06 Dec",
    "price": null,
    "currency": "USD",
    "availability": "Enquire",
    "totalCapacity": 50,
    "image": "/images/circuits/abudhabi.jpg",
    "tier": "hero",
    "duration": "3_day",
    "includes": [
      "Hospitality Access",
      "Race Viewing",
      "Refreshments"
    ],
    "featured": false,
    "raceId": "abudhabi-2026"
  },
  {
    "id": "abudhabi-west-straight-2026",
    "name": "3 Day West Straight",
    "circuit": "Abu Dhabi Grand Prix",
    "location": "Yas Marina",
    "country": "UAE",
    "countryCode": "AE",
    "date": "2026-12-06",
    "dateRange": "04 - 06 Dec",
    "price": 1075,
    "currency": "USD",
    "availability": "Enquire",
    "totalCapacity": 50,
    "image": "/images/circuits/abudhabi.jpg",
    "tier": "hero",
    "duration": "3_day",
    "includes": [
      "Hospitality Access",
      "Race Viewing",
      "Refreshments"
    ],
    "featured": false,
    "raceId": "abudhabi-2026"
  },
  {
    "id": "abudhabi-north-straight-2026",
    "name": "3 Day North Straight",
    "circuit": "Abu Dhabi Grand Prix",
    "location": "Yas Marina",
    "country": "UAE",
    "countryCode": "AE",
    "date": "2026-12-06",
    "dateRange": "04 - 06 Dec",
    "price": 955,
    "currency": "USD",
    "availability": "Enquire",
    "totalCapacity": 50,
    "image": "/images/circuits/abudhabi.jpg",
    "tier": "hero",
    "duration": "3_day",
    "includes": [
      "Hospitality Access",
      "Race Viewing",
      "Refreshments"
    ],
    "featured": false,
    "raceId": "abudhabi-2026"
  }
] as unknown as Package[]
