/** Past-event packages (before Canada 2026) — kept when not on live inventory sheet. */
import type { Package } from "../types/catalog"

export const pastPackages2026: Package[] = [
  // Australian GP
  {
    id: "australia-legend-paddock-club-2026",
    name: "Legend Paddock Club",
    circuit: "Australian Grand Prix",
    location: "Melbourne",
    country: "Australia",
    countryCode: "AU",
    date: "2026-03-08",
    dateRange: "06 - 08 Mar",
    price: null,
    currency: "USD",
    availability: "Enquire",
    totalCapacity: 50,
    image: "/images/circuits/melbourne.jpg",
    tier: "legend",
    includes: ["Paddock Club Access", "Premium Dining", "Open Bar", "Pit Lane Walk", "Driver Appearances"],
  },
  {
    id: "australia-f1-experiences-paddock-club-2026",
    name: "F1 Experiences Paddock Club",
    circuit: "Australian Grand Prix",
    location: "Melbourne",
    country: "Australia",
    countryCode: "AU",
    date: "2026-03-08",
    dateRange: "06 - 08 Mar",
    price: null,
    currency: "USD",
    availability: "Enquire",
    totalCapacity: 50,
    image: "/images/circuits/melbourne.jpg",
    tier: "paddock",
    includes: ["Paddock Access", "Gourmet Dining", "Open Bar", "Pit Lane Walk"],
  },
  {
    id: "australia-paddock-club-suite-2026",
    name: "Paddock Club - Club Suite",
    circuit: "Australian Grand Prix",
    location: "Melbourne",
    country: "Australia",
    countryCode: "AU",
    date: "2026-03-08",
    dateRange: "06 - 08 Mar",
    price: null,
    currency: "USD",
    availability: "Enquire",
    totalCapacity: 50,
    image: "/images/circuits/melbourne.jpg",
    tier: "paddock",
    includes: ["Paddock Access", "Gourmet Dining", "Open Bar", "Pit Lane Walk"],
  },
  {
    id: "australia-champions-club-2026",
    name: "Champions Club",
    circuit: "Australian Grand Prix",
    location: "Melbourne",
    country: "Australia",
    countryCode: "AU",
    date: "2026-03-08",
    dateRange: "06 - 08 Mar",
    price: null,
    currency: "USD",
    availability: "Enquire",
    totalCapacity: 50,
    image: "/images/circuits/melbourne.jpg",
    tier: "champions",
    includes: ["Grandstand Seats", "Hospitality Suite", "Gourmet Lunch", "Pit Lane Walk"],
  },
  // Chinese GP
  {
    id: "china-gordon-ramsey-paddock-2026",
    name: "Gordon Ramsey at the Paddock Club",
    circuit: "Chinese Grand Prix",
    location: "Shanghai",
    country: "China",
    countryCode: "CN",
    date: "2026-03-15",
    dateRange: "13 - 15 Mar",
    price: 17500,
    currency: "USD",
    availability: "Enquire",
    totalCapacity: 50,
    image: "/images/circuits/shanghai.jpg",
    tier: "paddock",
    includes: ["Paddock Access", "Gourmet Dining", "Open Bar", "Pit Lane Walk"],
  },
  {
    id: "china-legend-paddock-club-2026",
    name: "Legend Paddock Club",
    circuit: "Chinese Grand Prix",
    location: "Shanghai",
    country: "China",
    countryCode: "CN",
    date: "2026-03-15",
    dateRange: "13 - 15 Mar",
    price: 9750,
    currency: "USD",
    availability: "Enquire",
    totalCapacity: 50,
    image: "/images/circuits/shanghai.jpg",
    tier: "legend",
    includes: ["Paddock Club Access", "Premium Dining", "Open Bar", "Pit Lane Walk", "Driver Appearances"],
  },
  {
    id: "china-paddock-club-audi-2026",
    name: "Paddock Club - Audi F1",
    circuit: "Chinese Grand Prix",
    location: "Shanghai",
    country: "China",
    countryCode: "CN",
    date: "2026-03-15",
    dateRange: "13 - 15 Mar",
    price: 9889,
    currency: "USD",
    availability: "Enquire",
    totalCapacity: 50,
    image: "/images/circuits/shanghai.jpg",
    tier: "paddock",
    includes: ["Paddock Access", "Gourmet Dining", "Open Bar", "Pit Lane Walk"],
  },
  {
    id: "china-f1-experiences-paddock-request-2026",
    name: "F1 Experiences Paddock Club",
    circuit: "Chinese Grand Prix",
    location: "Shanghai",
    country: "China",
    countryCode: "CN",
    date: "2026-03-15",
    dateRange: "13 - 15 Mar",
    price: 6650,
    currency: "USD",
    availability: "Request",
    totalCapacity: 50,
    image: "/images/circuits/shanghai.jpg",
    tier: "paddock",
    includes: ["Paddock Access", "Gourmet Dining", "Open Bar", "Pit Lane Walk"],
  },
  {
    id: "china-paddock-club-suite-f1-2026",
    name: "Paddock Club - Club Suite (F1)",
    circuit: "Chinese Grand Prix",
    location: "Shanghai",
    country: "China",
    countryCode: "CN",
    date: "2026-03-15",
    dateRange: "13 - 15 Mar",
    price: 6750,
    currency: "USD",
    availability: 14,
    totalCapacity: 30,
    image: "/images/circuits/shanghai.jpg",
    tier: "paddock",
    includes: ["Paddock Access", "Gourmet Dining", "Open Bar", "Pit Lane Walk"],
  },
  {
    id: "china-champions-club-2026",
    name: "Champions Club",
    circuit: "Chinese Grand Prix",
    location: "Shanghai",
    country: "China",
    countryCode: "CN",
    date: "2026-03-15",
    dateRange: "13 - 15 Mar",
    price: 4999,
    currency: "USD",
    availability: "Enquire",
    totalCapacity: 50,
    image: "/images/circuits/shanghai.jpg",
    tier: "champions",
    includes: ["Grandstand Seats", "Hospitality Suite", "Gourmet Lunch", "Pit Lane Walk"],
  },
  // Japanese GP
  {
    id: "japan-paddock-club-house-44-2026",
    name: "Paddock Club - House 44",
    circuit: "Japanese Grand Prix",
    location: "Suzuka",
    country: "Japan",
    countryCode: "JP",
    date: "2026-03-29",
    dateRange: "27 - 29 Mar",
    price: 16500,
    currency: "USD",
    availability: "Enquire",
    totalCapacity: 50,
    image: "/images/circuits/suzuka.jpg",
    tier: "paddock",
    includes: ["Paddock Access", "Gourmet Dining", "Open Bar", "Pit Lane Walk"],
  },
  {
    id: "japan-paddock-club-red-bull-2026",
    name: "Paddock Club - Red Bull",
    circuit: "Japanese Grand Prix",
    location: "Suzuka",
    country: "Japan",
    countryCode: "JP",
    date: "2026-03-29",
    dateRange: "27 - 29 Mar",
    price: 10229,
    currency: "USD",
    availability: "Enquire",
    totalCapacity: 50,
    image: "/images/circuits/suzuka.jpg",
    tier: "paddock",
    includes: ["Paddock Access", "Gourmet Dining", "Open Bar", "Pit Lane Walk"],
  },
  {
    id: "japan-paddock-club-audi-2026",
    name: "Paddock Club - Audi",
    circuit: "Japanese Grand Prix",
    location: "Suzuka",
    country: "Japan",
    countryCode: "JP",
    date: "2026-03-29",
    dateRange: "27 - 29 Mar",
    price: 9889,
    currency: "USD",
    availability: "Enquire",
    totalCapacity: 50,
    image: "/images/circuits/suzuka.jpg",
    tier: "paddock",
    includes: ["Paddock Access", "Gourmet Dining", "Open Bar", "Pit Lane Walk"],
  },
  {
    id: "japan-legend-paddock-club-2026",
    name: "Legend Paddock Club",
    circuit: "Japanese Grand Prix",
    location: "Suzuka",
    country: "Japan",
    countryCode: "JP",
    date: "2026-03-29",
    dateRange: "27 - 29 Mar",
    price: 10845,
    currency: "USD",
    availability: "Enquire",
    totalCapacity: 50,
    image: "/images/circuits/suzuka.jpg",
    tier: "legend",
    includes: ["Paddock Club Access", "Premium Dining", "Open Bar", "Pit Lane Walk", "Driver Appearances"],
  },
  {
    id: "japan-f1-experiences-paddock-club-2026",
    name: "F1 Experiences Paddock Club",
    circuit: "Japanese Grand Prix",
    location: "Suzuka",
    country: "Japan",
    countryCode: "JP",
    date: "2026-03-29",
    dateRange: "27 - 29 Mar",
    price: 8500,
    currency: "USD",
    availability: 3,
    totalCapacity: 10,
    image: "/images/circuits/suzuka.jpg",
    tier: "paddock",
    includes: ["Paddock Access", "Gourmet Dining", "Open Bar", "Pit Lane Walk"],
  },
  {
    id: "japan-paddock-club-club-suite-2026",
    name: "Paddock Club - Club Suite",
    circuit: "Japanese Grand Prix",
    location: "Suzuka",
    country: "Japan",
    countryCode: "JP",
    date: "2026-03-29",
    dateRange: "27 - 29 Mar",
    price: 6325,
    currency: "USD",
    availability: "Enquire",
    totalCapacity: 50,
    image: "/images/circuits/suzuka.jpg",
    tier: "paddock",
    includes: ["Paddock Access", "Gourmet Dining", "Open Bar", "Pit Lane Walk"],
  },
  {
    id: "japan-champions-club-2026",
    name: "Champions Club",
    circuit: "Japanese Grand Prix",
    location: "Suzuka",
    country: "Japan",
    countryCode: "JP",
    date: "2026-03-29",
    dateRange: "27 - 29 Mar",
    price: 4509,
    currency: "USD",
    availability: "Enquire",
    totalCapacity: 50,
    image: "/images/circuits/suzuka.jpg",
    tier: "champions",
    includes: ["Grandstand Seats", "Hospitality Suite", "Gourmet Lunch", "Pit Lane Walk"],
  },
  {
    id: "bahrain-legend-paddock-club-2026",
    name: "Legend Paddock Club - Club Suite",
    circuit: "Bahrain Grand Prix",
    location: "Sakhir",
    country: "Bahrain",
    countryCode: "BH",
    date: "2026-04-12",
    dateRange: "10 - 12 Apr",
    price: 11950,
    currency: "USD",
    availability: 8,
    totalCapacity: 12,
    image: "/images/circuits/bahrain.jpg",
    tier: "legend",
    includes: ["Club Suite Access", "Paddock Club Privileges", "Premium Dining", "Open Bar", "Pit Lane Walk", "Driver Appearances"],
  },
  {
    id: "bahrain-paddock-redbull-2026",
    name: "Paddock Club - Red Bull",
    circuit: "Bahrain Grand Prix",
    location: "Sakhir",
    country: "Bahrain",
    countryCode: "BH",
    date: "2026-04-12",
    dateRange: "10 - 12 Apr",
    price: 12500,
    currency: "USD",
    availability: 8,
    totalCapacity: 12,
    image: "/images/circuits/bahrain.jpg",
    tier: "paddock",
    includes: ["Red Bull Hospitality", "Paddock Access", "Premium Dining", "Open Bar", "Pit Lane Walk", "Team Access"],
  },
  {
    id: "bahrain-paddock-club-suite-2026",
    name: "Paddock Club - Club Suite",
    circuit: "Bahrain Grand Prix",
    location: "Sakhir",
    country: "Bahrain",
    countryCode: "BH",
    date: "2026-04-12",
    dateRange: "10 - 12 Apr",
    price: 9500,
    currency: "USD",
    availability: 20,
    totalCapacity: 30,
    image: "/images/circuits/bahrain.jpg",
    tier: "paddock",
    includes: ["Club Suite Access", "Paddock Access", "Gourmet Dining", "Open Bar", "Pit Lane Walk"],
  },
  {
    id: "bahrain-champions-beyon-2026",
    name: "Champions Club - Beyon",
    circuit: "Bahrain Grand Prix",
    location: "Sakhir",
    country: "Bahrain",
    countryCode: "BH",
    date: "2026-04-12",
    dateRange: "10 - 12 Apr",
    price: 3499,
    currency: "USD",
    availability: 10,
    totalCapacity: 25,
    image: "/images/circuits/bahrain.jpg",
    tier: "champions",
    includes: ["Beyon Hospitality", "Grandstand Seats", "Hospitality Suite", "Gourmet Lunch", "Pit Lane Walk"],
  },
  {
    id: "bahrain-dome-2026",
    name: "The Dome",
    circuit: "Bahrain Grand Prix",
    location: "Sakhir",
    country: "Bahrain",
    countryCode: "BH",
    date: "2026-04-12",
    dateRange: "10 - 12 Apr",
    price: 1125,
    currency: "USD",
    availability: 10,
    totalCapacity: 25,
    image: "/images/circuits/bahrain.jpg",
    tier: "hero",
    includes: ["Dome Hospitality", "Grandstand Seats", "Refreshments", "Race Viewing"],
  },
  // Saudi Arabian GP
  {
    id: "saudi-legend-paddock-club-2026",
    name: "Legend Paddock Club",
    circuit: "Saudi Arabian Grand Prix",
    location: "Jeddah",
    country: "Saudi Arabia",
    countryCode: "SA",
    date: "2026-04-19",
    dateRange: "17 - 19 Apr",
    price: 12999,
    currency: "USD",
    availability: 10,
    totalCapacity: 30,
    image: "/images/circuits/jeddah.jpg",
    tier: "legend",
    includes: ["Paddock Club Access", "Premium Dining", "Open Bar", "Pit Lane Walk", "Driver Appearances"],
  },
  {
    id: "saudi-f1-experiences-paddock-club-2026",
    name: "F1 Experiences Paddock Club",
    circuit: "Saudi Arabian Grand Prix",
    location: "Jeddah",
    country: "Saudi Arabia",
    countryCode: "SA",
    date: "2026-04-19",
    dateRange: "17 - 19 Apr",
    price: 9500,
    currency: "USD",
    availability: 10,
    totalCapacity: 30,
    image: "/images/circuits/jeddah.jpg",
    tier: "paddock",
    includes: ["Paddock Access", "Gourmet Dining", "Open Bar", "Pit Lane Walk"],
  },
  {
    id: "saudi-paddock-club-red-bull-2026",
    name: "Paddock Club - Red Bull",
    circuit: "Saudi Arabian Grand Prix",
    location: "Jeddah",
    country: "Saudi Arabia",
    countryCode: "SA",
    date: "2026-04-19",
    dateRange: "17 - 19 Apr",
    price: 11650,
    currency: "USD",
    availability: 10,
    totalCapacity: 30,
    image: "/images/circuits/jeddah.jpg",
    tier: "paddock",
    includes: ["Paddock Access", "Gourmet Dining", "Open Bar", "Pit Lane Walk"],
  },
  {
    id: "saudi-paddock-club-club-suite-2026",
    name: "Paddock Club - Club Suite",
    circuit: "Saudi Arabian Grand Prix",
    location: "Jeddah",
    country: "Saudi Arabia",
    countryCode: "SA",
    date: "2026-04-19",
    dateRange: "17 - 19 Apr",
    price: null,
    currency: "USD",
    availability: "Enquire",
    totalCapacity: 50,
    image: "/images/circuits/jeddah.jpg",
    tier: "paddock",
    includes: ["Paddock Access", "Gourmet Dining", "Open Bar", "Pit Lane Walk"],
  },
  {
    id: "saudi-champions-club-2026",
    name: "Champions Club",
    circuit: "Saudi Arabian Grand Prix",
    location: "Jeddah",
    country: "Saudi Arabia",
    countryCode: "SA",
    date: "2026-04-19",
    dateRange: "17 - 19 Apr",
    price: null,
    currency: "USD",
    availability: "Enquire",
    totalCapacity: 50,
    image: "/images/circuits/jeddah.jpg",
    tier: "champions",
    includes: ["Grandstand Seats", "Hospitality Suite", "Gourmet Lunch", "Pit Lane Walk"],
  },
  // Miami GP
  {
    id: "miami-legend-paddock-club-2026",
    name: "Legend Paddock Club",
    circuit: "Miami Grand Prix",
    location: "Miami Gardens",
    country: "United States",
    countryCode: "US",
    date: "2026-05-03",
    dateRange: "01 - 03 May",
    price: null,
    currency: "USD",
    availability: "Sold Out",
    totalCapacity: 50,
    image: "/images/circuits/miami.jpg",
    tier: "legend",
    includes: ["Paddock Club Access", "Premium Dining", "Open Bar", "Pit Lane Walk", "Driver Appearances"],
  },
  {
    id: "miami-f1-experiences-paddock-club-2026",
    name: "F1 Experiences Paddock Club",
    circuit: "Miami Grand Prix",
    location: "Miami Gardens",
    country: "United States",
    countryCode: "US",
    date: "2026-05-03",
    dateRange: "01 - 03 May",
    price: null,
    currency: "USD",
    availability: "Sold Out",
    totalCapacity: 50,
    image: "/images/circuits/miami.jpg",
    tier: "paddock",
    includes: ["Paddock Access", "Gourmet Dining", "Open Bar", "Pit Lane Walk"],
  },
  {
    id: "miami-paddock-club-club-suite-2026",
    name: "Paddock Club - Club Suite",
    circuit: "Miami Grand Prix",
    location: "Miami Gardens",
    country: "United States",
    countryCode: "US",
    date: "2026-05-03",
    dateRange: "01 - 03 May",
    price: null,
    currency: "USD",
    availability: "Sold Out",
    totalCapacity: 50,
    image: "/images/circuits/miami.jpg",
    tier: "paddock",
    includes: ["Paddock Access", "Gourmet Dining", "Open Bar", "Pit Lane Walk"],
  },
  {
    id: "miami-champions-club-2026",
    name: "Champions Club",
    circuit: "Miami Grand Prix",
    location: "Miami Gardens",
    country: "United States",
    countryCode: "US",
    date: "2026-05-03",
    dateRange: "01 - 03 May",
    price: null,
    currency: "USD",
    availability: "Sold Out",
    totalCapacity: 50,
    image: "/images/circuits/miami.jpg",
    tier: "champions",
    includes: ["Grandstand Seats", "Hospitality Suite", "Gourmet Lunch", "Pit Lane Walk"],
  },
]

