/** Mock catalog seed data � used only by `scripts/seed-catalog.ts`. */
import type { Booking, Invoice, Package, Race } from "./types/catalog"
import { pastPackages2026 } from "./seed-data/past-packages-2026"
import { livePackages2026 } from "./seed-data/live-packages-2026"

export const races2026: Race[] = [
  {
    id: "australia-2026",
    name: "Australian Grand Prix",
    shortName: "Australia",
    location: "Melbourne",
    country: "Australia",
    countryCode: "AU",
    date: "2026-03-08",
    dateRange: "06 - 08 Mar",
    image: "/images/circuits/melbourne.jpg",
    packagesAvailable: 6,
    lowestPrice: 3900,
  },
  {
    id: "china-2026",
    name: "Chinese Grand Prix",
    shortName: "China",
    location: "Shanghai",
    country: "China",
    countryCode: "CN",
    date: "2026-03-15",
    dateRange: "13 - 15 Mar",
    image: "/images/circuits/shanghai.jpg",
    packagesAvailable: 7,
    lowestPrice: 3600,
  },
  {
    id: "japan-2026",
    name: "Japanese Grand Prix",
    shortName: "Japan",
    location: "Suzuka",
    country: "Japan",
    countryCode: "JP",
    date: "2026-03-29",
    dateRange: "27 - 29 Mar",
    image: "/images/circuits/suzuka.jpg",
    packagesAvailable: 3,
    lowestPrice: 5200,
  },
  {
    id: "bahrain-2026",
    name: "Bahrain Grand Prix",
    shortName: "Bahrain",
    location: "Sakhir",
    country: "Bahrain",
    countryCode: "BH",
    date: "2026-04-12",
    dateRange: "10 - 12 Apr",
    image: "/images/circuits/bahrain.jpg",
    packagesAvailable: 5,
    lowestPrice: 1125,
  },
  {
    id: "saudi-2026",
    name: "Saudi Arabian Grand Prix",
    shortName: "Saudi Arabia",
    location: "Jeddah",
    country: "Saudi Arabia",
    countryCode: "SA",
    date: "2026-04-19",
    dateRange: "17 - 19 Apr",
    image: "/images/circuits/jeddah.jpg",
    packagesAvailable: 4,
    lowestPrice: 4800,
  },
  {
    id: "miami-2026",
    name: "Miami Grand Prix",
    shortName: "Miami",
    location: "Miami Gardens",
    country: "United States",
    countryCode: "US",
    date: "2026-05-03",
    dateRange: "01 - 03 May",
    image: "/images/circuits/miami.jpg",
    packagesAvailable: 8,
    lowestPrice: 4500,
  },
  {
    id: "canada-2026",
    name: "Canadian Grand Prix",
    shortName: "Canada",
    location: "Montreal",
    country: "Canada",
    countryCode: "CA",
    date: "2026-05-24",
    dateRange: "22 - 24 May",
    image: "/images/circuits/montreal.jpg",
    packagesAvailable: 5,
    lowestPrice: 3800,
  },
  {
    id: "monaco-2026",
    name: "Monaco Grand Prix",
    shortName: "Monaco",
    location: "Monte Carlo",
    country: "Monaco",
    countryCode: "MC",
    date: "2026-06-07",
    dateRange: "05 - 07 Jun",
    image: "/images/circuits/monaco.jpg",
    packagesAvailable: 3,
    lowestPrice: 8500,
  },
  {
    id: "spain-2026",
    name: "Barcelona Grand Prix",
    shortName: "Barcelona",
    location: "Barcelona",
    country: "Spain",
    countryCode: "ES",
    date: "2026-06-14",
    dateRange: "12 - 14 Jun",
    image: "/images/circuits/barcelona.jpg",
    packagesAvailable: 6,
    lowestPrice: 3400,
  },
  {
    id: "austria-2026",
    name: "Austrian Grand Prix",
    shortName: "Austria",
    location: "Spielberg",
    country: "Austria",
    countryCode: "AT",
    date: "2026-06-28",
    dateRange: "26 - 28 Jun",
    image: "/images/circuits/spielberg.jpg",
    packagesAvailable: 4,
    lowestPrice: 3200,
  },
  {
    id: "britain-2026",
    name: "British Grand Prix",
    shortName: "Great Britain",
    location: "Silverstone",
    country: "United Kingdom",
    countryCode: "GB",
    date: "2026-07-05",
    dateRange: "03 - 05 Jul",
    image: "/images/circuits/silverstone.jpg",
    packagesAvailable: 6,
    lowestPrice: 4200,
  },
  {
    id: "belgium-2026",
    name: "Belgian Grand Prix",
    shortName: "Belgium",
    location: "Spa-Francorchamps",
    country: "Belgium",
    countryCode: "BE",
    date: "2026-07-19",
    dateRange: "17 - 19 Jul",
    image: "/images/circuits/spa.jpg",
    packagesAvailable: 4,
    lowestPrice: 4600,
  },
  {
    id: "hungary-2026",
    name: "Hungarian Grand Prix",
    shortName: "Hungary",
    location: "Budapest",
    country: "Hungary",
    countryCode: "HU",
    date: "2026-07-26",
    dateRange: "24 - 26 Jul",
    image: "/images/circuits/budapest.jpg",
    packagesAvailable: 5,
    lowestPrice: 3100,
  },
  {
    id: "netherlands-2026",
    name: "Dutch Grand Prix",
    shortName: "Netherlands",
    location: "Zandvoort",
    country: "Netherlands",
    countryCode: "NL",
    date: "2026-08-23",
    dateRange: "21 - 23 Aug",
    image: "/images/circuits/zandvoort.jpg",
    packagesAvailable: 3,
    lowestPrice: 4900,
  },
  {
    id: "italy-2026",
    name: "Italian Grand Prix",
    shortName: "Italy",
    location: "Monza",
    country: "Italy",
    countryCode: "IT",
    date: "2026-09-06",
    dateRange: "04 - 06 Sep",
    image: "/images/circuits/monza.jpg",
    packagesAvailable: 5,
    lowestPrice: 4300,
  },
  {
    id: "madrid-2026",
    name: "Spanish Grand Prix",
    shortName: "Spain",
    location: "Madrid",
    country: "Spain",
    countryCode: "ES",
    date: "2026-09-13",
    dateRange: "11 - 13 Sep",
    image: "/images/circuits/madrid.jpg",
    packagesAvailable: 4,
    lowestPrice: 4100,
  },
  {
    id: "azerbaijan-2026",
    name: "Azerbaijan Grand Prix",
    shortName: "Azerbaijan",
    location: "Baku",
    country: "Azerbaijan",
    countryCode: "AZ",
    date: "2026-09-26",
    dateRange: "24 - 26 Sep",
    image: "/images/circuits/baku.jpg",
    packagesAvailable: 4,
    lowestPrice: 3700,
  },
  {
    id: "singapore-2026",
    name: "Singapore Grand Prix",
    shortName: "Singapore",
    location: "Marina Bay",
    country: "Singapore",
    countryCode: "SG",
    date: "2026-10-11",
    dateRange: "09 - 11 Oct",
    image: "/images/circuits/singapore.jpg",
    packagesAvailable: 5,
    lowestPrice: 5500,
  },
  {
    id: "usa-2026",
    name: "United States Grand Prix",
    shortName: "Austin",
    location: "Austin",
    country: "United States",
    countryCode: "US",
    date: "2026-10-25",
    dateRange: "23 - 25 Oct",
    image: "/images/circuits/austin.jpg",
    packagesAvailable: 7,
    lowestPrice: 3800,
  },
  {
    id: "mexico-2026",
    name: "Mexico City Grand Prix",
    shortName: "Mexico",
    location: "Mexico City",
    country: "Mexico",
    countryCode: "MX",
    date: "2026-11-01",
    dateRange: "30 Oct - 01 Nov",
    image: "/images/circuits/mexico.jpg",
    packagesAvailable: 6,
    lowestPrice: 3200,
  },
  {
    id: "brazil-2026",
    name: "São Paulo Grand Prix",
    shortName: "Brazil",
    location: "São Paulo",
    country: "Brazil",
    countryCode: "BR",
    date: "2026-11-08",
    dateRange: "06 - 08 Nov",
    image: "/images/circuits/interlagos.jpg",
    packagesAvailable: 5,
    lowestPrice: 3500,
  },
  {
    id: "vegas-2026",
    name: "Las Vegas Grand Prix",
    shortName: "Las Vegas",
    location: "Las Vegas",
    country: "United States",
    countryCode: "US",
    date: "2026-11-21",
    dateRange: "19 - 21 Nov",
    image: "/images/circuits/vegas.jpg",
    packagesAvailable: 4,
    lowestPrice: 6200,
  },
  {
    id: "qatar-2026",
    name: "Qatar Grand Prix",
    shortName: "Qatar",
    location: "Lusail",
    country: "Qatar",
    countryCode: "QA",
    date: "2026-11-29",
    dateRange: "27 - 29 Nov",
    image: "/images/circuits/lusail.jpg",
    packagesAvailable: 4,
    lowestPrice: 4400,
  },
  {
    id: "abudhabi-2026",
    name: "Abu Dhabi Grand Prix",
    shortName: "Abu Dhabi",
    location: "Yas Marina",
    country: "UAE",
    countryCode: "AE",
    date: "2026-12-06",
    dateRange: "04 - 06 Dec",
    image: "/images/circuits/abudhabi.jpg",
    packagesAvailable: 3,
    lowestPrice: 7800,
  },
]

export const packages: Package[] = [...pastPackages2026, ...livePackages2026]

export const bookings: Booking[] = [
  {
    id: "BK-2026-001",
    packageId: "monaco-paddock-2026",
    packageName: "Monaco GP - Paddock Club",
    circuit: "Monaco Grand Prix",
    date: "2026-05-24",
    guests: 4,
    invoiceStatus: "paid",
    totalAmount: 34000,
    currency: "USD",
    createdAt: "2026-01-15",
    clientName: "James Morrison",
    clientEmail: "james@morrison-corp.com",
  },
  {
    id: "BK-2026-002",
    packageId: "silverstone-champions-2026",
    packageName: "British GP - Champions Club",
    circuit: "British Grand Prix",
    date: "2026-07-05",
    guests: 6,
    invoiceStatus: "awaiting_invoice",
    totalAmount: 31200,
    currency: "USD",
    createdAt: "2026-01-18",
    clientName: "Sarah Chen",
    clientEmail: "schen@techventures.io",
  },
  {
    id: "BK-2026-003",
    packageId: "abudhabi-legend-2026",
    packageName: "Abu Dhabi GP - Legend Package",
    circuit: "Abu Dhabi Grand Prix",
    date: "2026-12-06",
    guests: 2,
    invoiceStatus: "awaiting_payment",
    totalAmount: 18400,
    currency: "USD",
    createdAt: "2026-01-20",
    clientName: "Marcus Webb",
    clientEmail: "m.webb@luxurytravel.com",
  },
]

export const invoices: Invoice[] = [
  {
    id: "INV-2026-001",
    bookingId: "BK-2026-001",
    amount: 34000,
    currency: "USD",
    status: "paid",
    issuedAt: "2026-01-15",
    packageName: "Monaco GP - Paddock Club",
  },
  {
    id: "INV-2026-002",
    bookingId: "BK-2026-002",
    amount: 31200,
    currency: "USD",
    status: "awaiting_invoice",
    issuedAt: null,
    packageName: "British GP - Champions Club",
  },
  {
    id: "INV-2026-003",
    bookingId: "BK-2026-003",
    amount: 18400,
    currency: "USD",
    status: "awaiting_payment",
    issuedAt: "2025-12-20",
    packageName: "Abu Dhabi GP - Legend Package",
  },
]
